### ISSUE TITLE
GET request with HTTP Body

### ISSUE THREAD

**Issue by rawkode** [teamon/tesla#107]
I am trying to make GraphQL requests with Tesla, which requires a body on a GET request. I've tried reading the docs and adapters and calling code I believe should work, but sadly to no avail.

Could you please provide an example of this?

**Comment by amatalai** [comment]
Hi, try this

```elixir
defmodule Client do
  use Tesla
  adapter :hackney

  def get_with_body do
     request(method: :get, url: "http://httpbin.org/anything", body: "foo bar")
  end
end
```

**Comment by rawkode** [comment]
I already tried that with `httpc`, and it failed. I'll add the `hackey` adapter and let you know.

Thanks :+1:

**Comment by amatalai** [comment]
Yeah, `httpc` failed for me too. I think it doesn't support get with body.

**Comment by rawkode** [comment]
Works with `hackey`.

Thanks @amatalai
