### ISSUE TITLE
How to use Tesla.Middleware.BaseUrlFromConfig

### ISSUE THREAD

**Issue by edescourtis** [teamon/tesla#118]
Please provide an example or basic documentation how to use `Tesla.Middleware.BaseUrlFromConfig`.

**Comment by amatalai** [comment]
Hi, I believe this should work like this
```elixir
#lib/my_app/api
defmodule MyApp.Api do
  use Tesla
  plug Tesla.Middleware.BaseUrlFromConfig, otp_app: :my_app, module: __MODULE__

  #...
end

# config/config.exs
config :my_app, MyApp.Api, base_url: "http://example.com/" 
```

**Comment by teamon** [comment]
I've skipped documentation for this module on purpose - it is there only to keep backwards compatibility.

The most robust way to have a runtime/release/ENV-enabled configuration is to use it like this:

```ex
defmodule MyApi do
  use Tesla
  plug Tesla.Middleware.BaseUrl, base_url()

  def base_url do
    Application.fetch_env!(:myapp, :api_url)
  end
end
```

**Comment by edescourtis** [comment]
Thanks that is really helpful!
