### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by tompave** [teamon/tesla#121]
At the moment it's a bit hard to update Tesla because the repository doesn't have a changelog. To upgrade, it's necessary to go and look at all the commits between releases, which is tedious, time consuming and error prone.

Would it be possible to add a changelog file with all the previous releases and update it with any new release?

**Comment by amatalai** [comment]
Hi @tompave , 
Teamon documented every change starting from Tesla 0.5.2 in github releases page
<img width="1049" alt="releases" src="https://user-images.githubusercontent.com/5769780/31531476-ad27d46c-afe7-11e7-8d49-b0326d06a5f6.png">

<img width="1014" alt="screen shot 2017-10-13 at 07 26 17" src="https://user-images.githubusercontent.com/5769780/31531533-fc96a898-afe7-11e7-8fea-d5582721b30f.png">

**Comment by tompave** [comment]
Oh, nice. I missed that. Thanks.

**Comment by teamon** [comment]
Thanks for answering @amatalai 
I've just added a "Changelog" link to README, just in case.

**Comment by amatalai** [comment]
👍
