### ISSUE TITLE
Mock adapter does not decode JSON

### ISSUE THREAD

**Issue by starbelly** [teamon/tesla#124]
This may be a feature and not a bug, but not what I was expecting.  If I have time I will try to dig in and figure out the problem, if there is a problem. In the mean time I switched my app to just use the encode middleware and handle decoding manually.

 By the way, this is an absolutely awesome elixir app 👍 

# Example

## mix.exs
```elixir
defmodule MyApp.Mixfile do
  use Mix.Project

  def project do
    [
      app: :my_app,
      version: "0.1.0",
      elixir: "~> 1.5",
      start_permanent: Mix.env == :prod,
      deps: deps()
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp deps do
    [{:tesla, "~> 0.9.0"},
    {:poison, ">= 1.0.0"}]
  end
end
```

## config/test.exs
```elixir
use Mix.Config
config :tesla, adapter: :mock
```

## lib/MyApp.ex
```elixir
defmodule MyApp do
  use Tesla
  plug Tesla.Middleware.BaseUrl, "http://example.com"
  plug Tesla.Middleware.JSON
end
```

## test/myapp_test.exs
```elixir
defmodule MyAppTest do
  use ExUnit.Case

   setup do
    Tesla.Mock.mock fn
      %{method: :get, url: "http://example.com/json"} ->
        %Tesla.Env{status: 200, body: "[{}]"}
    end
    :ok
  end

  test "mock adapter calls middleware to decode json" do
    assert %Tesla.Env{} = env = MyApp.get("/json")
    assert env.status == 200
    assert env.body == [{}]
  end
end
```
## Result
```shell
 1) test mock adapter calls middleware to decode json (MyAppTest)
     test/my_app_test.exs:14
     Assertion with == failed
     code:  assert env.body() == [{}]
     left:  "[{}]"
     right: [{}]
     stacktrace:
       test/problem_test.exs:17: (test)



Finished in 0.05 seconds
1 test, 1 failure
```

**Comment by teamon** [comment]
JSON Middleware checks Content-Type header when deciding if it should decode the body so you'll need to pass that, or just pass an already decoded one as mock, but keep in mind it must be only map/list/string (no atoms or tuples)

**Comment by teamon** [comment]
already decoded body*

**Comment by starbelly** [comment]
I see! Great :)  Note that  I did try to do that prior to opening this issue and ran into an issue: 


```elixir
...
 setup do
    Tesla.Mock.mock fn
      %{method: :get, url: "http://example.com/json"} ->
        %Tesla.Env{status: 200, body: [%{}]}
    end
...
```

Result:

```shell
 1) test mock adapter calls middleware to decode json (MyAppTest)
     test/my_app_test.exs:13
     Assertion with == failed
     code:  assert env.body() == [{}]
     left:  "{}"
     right: [{}]
     stacktrace:
       test/my_app_test.exs:16: (test)
```

I think something like this in middleware/core.ex would solve the issue: 

```elixir
iex(16)> defmodule Test do
...(16)> def foo(data) when is_map(hd(data)), do: IO.puts "it's a list of maps"
...(16)> def foo(data) when is_list(data), do: IO.puts "default to io list"
...(16)> end
{:module, Test,
 <<70, 79, 82, 49, 0, 0, 4, 100, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 99,
   0, 0, 0, 11, 11, 69, 108, 105, 120, 105, 114, 46, 84, 101, 115, 116, 8, 95,
   95, 105, 110, 102, 111, 95, 95, 9, 102, ...>>, {:foo, 1}}
iex(17)> list_of_maps = [%{}, %{}, %{}]
[%{}, %{}, %{}]
iex(18)> list_of_str = ["Hello", ", ", "world"]
["Hello", ", ", "world"]
iex(19)> Test.foo
foo/1
iex(19)> Test.foo(list_of_str)
default to io list
:ok
iex(20)> Test.foo(list_of_maps)
it's a list of maps
:ok
iex(21)>
```

The above definitely could be better and should have more sanity checks before hitting the is_map() guard.

**Comment by starbelly** [comment]
Better...

```elixir
iex(8)> defmodule Test do
...(8)>    def foo(data) when is_list(data) do
...(8)>      case is_map(hd(data)) do
...(8)>        true -> "is map"
...(8)>        false -> "is not a map"
...(8)>      end
...(8)>    end
...(8)> end

{:module, Test,
 <<70, 79, 82, 49, 0, 0, 4, 20, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 84, 0,
   0, 0, 9, 11, 69, 108, 105, 120, 105, 114, 46, 84, 101, 115, 116, 8, 95, 95,
   105, 110, 102, 111, 95, 95, 9, 102, ...>>, {:foo, 1}}
iex(9)> Test.foo([""])
"is not a map"
iex(10)> Test.foo([%{}])
"is map"
iex(11)>
```

 Unless of course, there's a good reason the code doesn't already handle this case. If not, then I'll submit a PR.

**Comment by starbelly** [comment]
See https://github.com/teamon/tesla/pull/125

**Comment by amatalai** [comment]
Hi

> ```elixir
> iex(8)> defmodule Test do
> ...(8)>    def foo(data) when is_list(data) do
> ...(8)>      case is_map(hd(data)) do
> ...(8)>        true -> "is map"
> ...(8)>        false -> "is not a map"
> ...(8)>      end
> ...(8)>    end
> ...(8)> end
> ```

This approach is invalid for `["foo", %{"bar" => "baz"}]`,  which has valid json representation 
`"[\"foo\", {\"bar\": \"baz\"}]"`

It could be done as `case Enum.any?(data, &is_map/1) do`, but there's one more edge case
`[97, 115, 100, 102]` 
is this a four integers list after decoding or `'asdf'` before charlist => binary conversation?

Personally I would prefer this approach
```elixir
Tesla.Mock.mock fn
  %{method: :get, url: "http://example.com/json"} ->
    %Tesla.Env{status: 200, body: '[{}]', headers: %{"content-type" => "application/json"}}
  end
```
as it doesn't need any change in codebase to make mock work and is closer to how it works in reality

**Comment by starbelly** [comment]
@amatalai  See #125 , all tests passing.

**Comment by amatalai** [comment]
@starbelly yes, for one specific case. I meant that it should work for all possible cases.

Use those and it will fail:
- `["foo", %{"bar" => "baz"}]`
- `[97, 115, 100, 102]`

Both are valid decoded jsons. In second example it's not even possible to distinguish if it's charlist from adapter or decoded json passed to mock

**Comment by starbelly** [comment]
@amatalai I see and get what's your saying now.

**Comment by starbelly** [comment]
@amatalai Unless you know of a particular resolution to this problem, I'm gonna go ahead and close my PR in favor of doing away with this feature for the mock adapter.

**Comment by teamon** [comment]
I'd go with

```ex
def json(data) do
  %Tesla.Env{status: 200, body: Posion.encode!(data), headers: %{"content-type" => "application/json"}}
end

Tesla.Mock.mock fn
  env -> json(["some", "data"])
end
```

As @amatalai wrote, I don't think we can find a bullet-proof solution to handle any data structure as body since adapters always return a very specific ones.

**Comment by amatalai** [comment]
At the moment I don't see any solution that will be universal. 
As stated before I would prefer to use something like this:
```elixir
json = [...] |> Poison.encode!
Tesla.Mock.mock fn
  %{method: :get, url: "http://example.com/json"} ->
    %Tesla.Env{status: 200, body: json, headers: %{"content-type" => "application/json"}}
  end
```

**Comment by starbelly** [comment]
Closing PR #125

**Comment by starbelly** [comment]
Will close this issue in favor of new issue.
