### ISSUE TITLE
Enforce content type headers for mock adapter

### ISSUE THREAD

**Issue by starbelly** [teamon/tesla#126]
Currently it is possible to provide raw elixir data for the body parameter used by the mock adapter. This only works for some cases... It is not feasible to try and support every edge case in regard to using this feature. It would be nice if this feature went away and a policy that requires you set the content type header for a mock put in it's place. This eliminates complexity that comes via raw elixir body parameter and would make using the mock adapter a lot less confusing..

Desired behavior:

```elixir
data = [%{foo: :bar}]
Tesla.Mock.mock fn
  env -> %Tesla.Env{status: 200, body: Posion.encode!(data)}}
end
```

The above would result in an exception or warning...

***"No content type header provided to Tesla.Mock for request ..."***

Likewise, passing in elixir data for the body parameter would result in exception or warning. 

```elixir
data = [%{foo: :bar}]
Tesla.Mock.mock fn
  env -> %Tesla.Env{status: 200, body: data}
end
```

***"body parameter for Tesla.Mock must be a bitstring ..."***

**Comment by starbelly** [comment]
See #124  as a reference.

**Comment by teamon** [comment]
I know this might be a pain when mocking json, but believe me sometimes you do want to test response without content type. I think the best we can do is to add more examples to docs and maybe provide some helper functions in Tesla.Mock module that could be imported, such as already mentioned `json(body)` function.

**Comment by starbelly** [comment]
I agree 👍 Docs and helper functions is the better and more flexible way to go. Type enforcement was somewhat of a knee jerk reaction 😄   Will try to do a few PRs soon. Closing this, cheers!
