### ISSUE TITLE
:httpc missing in release

### ISSUE THREAD

**Issue by bmurithi** [teamon/tesla#127]
I noticed that `httpc` methods were raising `undef` errors in a release.

Consequently, I was forced to add `:inets` explicity to the applications in my `mix.exs` like so.

```elixir
  def application do
    [mod: {MyModule, []},
     applications: [:inets, :tesla]]
  end
```

Unless I'm missing something, it looks like `tesla` should either include `:httpc` as a dependency so it is resolved when building releases or note the issue during deployment.

**Comment by teamon** [comment]
As in https://github.com/teamon/tesla/commit/f2fb7d3c24e32950cb50b972bef7cbf01a1c5344 

> Rationale: Most of the time :inets will be included in the release anyway, so there is not much cost in including it by default.


Thanks @bmurithi !
