### ISSUE TITLE
🎁 1.0.0 Wishlist 

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#129]
I'd like to start a wishlist for **[1.0](https://github.com/teamon/tesla/milestone/1)** release. It should include any last breaking changes before moving into proper semver for future releases.

Please comment if you'd like tesla to have (or drop) something in the near future.

Here are mine:
- [ ] **New: Cache middleware** - I think we should have a decent HTTP cache middleware (like [faraday-http-cache](https://github.com/plataformatec/faraday-http-cache)) with pluggable backend (a simple interface of get/put) while handling all of the HTTP cache stuff
- [x] **Breaking: Drop aliases** - it is not widely used nor documented feature, aliases were never kept up to date and with current implementation they add a compile-time link from tesla builder to all adapters and middlewares. And there is no way to make them work for any custom middleware.
- [x] **Breaking: Drop support for old elixir releases** - Supporting 1.3 is starting to cause issues, maybe it should be dropped. Maybe.
- [x] **Breaking: Support non-unique headers** - Unique-key map is NOT a correct data structure for headers. Example issues: #37 and #155 
- [x] **(Maybe) Breaking: Better Logger** - Unified Logger & DebugLogger.
- [ ] **New: KeepRequest middleware** - #156 (good test for ensuring opts are propagated correctly)
- [ ] **New: `init/1`** - Compile-time callback for middlewares
- [x] **Breaking: Return `:ok/:error` tuples by default** - add `get!` versions
- [ ] **New: Global middleware** - allow adding global middleware (think instrumentation)

**Comment by joshuataylor** [comment]
Cache middleware would be amazing, this help a lot when developing against APIs that have a cache timer and you don't want to hammer their APIs.

**Comment by emerleite** [comment]
About cache, We're using a simple solution that will evolve to something like this. Feedbacks are wellcome.

https://github.com/emerleite/tesla_cache

**Comment by joshuataylor** [comment]
For cache,what I'm doing is reading the response headers for when the cache expires, then storing it with Cachex until then. A good API should return the cache timer (if the output is cached).

Otherwise storing on your end is going to be tricky as you might get stale data.

**Comment by teamon** [comment]
All the breaking changes are now available in `1.0` branch. New features will be moved into 1.1 milestone.

**Comment by teamon** [comment]
tesla `1.0.0-beta.1` is out! Additional features has been moved into 1.1 milestone.
