### ISSUE TITLE
Timeout middleware behaviour doesn't make sense

### ISSUE THREAD

**Issue by edescourtis** [teamon/tesla#130]
I am using Tesla to reach many servers some of which I expect to be down. My Tesla related code is generated by swagger codegen. I was expecting from the timeout middleware to return some sort of error such as {:error, :unavailable} or {:error, :timeout} or something similar. Instead, the calling process gets a kill signal which makes it very annoying to work around (especially so when generated from swagger). 

The Erlang philosophy is "let it crash" not "make it crash". The middleware needs to let the caller decide whether he should crash or not. Typically you want to handle expected cases (that includes expected errors) and to let it crash when something unexpected happens.

I will submit a PR later. How far back does Tesla support Elixir? Is supporting Elixir >= 1.3 enough?

**Comment by amatalai** [comment]
https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/timeout.ex#L37
This kills task linked to current process. I'm not sure yet, why tests didn't detect such thing.

**Comment by edescourtis** [comment]
PR is ready

**Comment by emerleite** [comment]
@amatalai @edescourtis We need to stop somehow because the request will continue.

**Comment by emerleite** [comment]
@edescourtis Your PR makes sense.

**Comment by teamon** [comment]
Fixed via #131
