### ISSUE TITLE
Dialyzer issue with Tesla.Client typespec

### ISSUE THREAD

**Issue by randycoulman** [teamon/tesla#132]
After upgrading my application from Tesla 0.7.2 to 0.9.0, I started seeing a warning when running Dialyzer.

Given the following code:

```elixir
  @spec client(String.t) :: Tesla.Env.client
  def client(api_token) do
    encoded_token = Base.encode64("#{api_token}:api_token")
    Tesla.build_client [
      {Tesla.Middleware.Headers, %{"Authorization" => "Basic #{encoded_token}"}}
    ]
  end
```

I began seeing this warning:

```
Invalid type specification for function 'Elixir.InvoiceTracker.TimeTracker':client/1. The success typing is (_) -> #{'__struct__':='Elixir.Tesla.Client', 'fun':='nil', 'post':=[any()], 'pre':=[any()]}
```

I also tried with `Tesla.Client.t` instead of `Tesla.Env.client` without success.

I was able to work around the error by changing my typespec to the less strict:

```elixir
@spec client(String.t) :: %Tesla.Client{}
```

I'm not sure what the root cause of this issue is or how to fix it.  If someone can give me some idea of what might be wrong here, I'd be happy to submit a PR with a fix.

**Comment by teamon** [comment]
Probably because Client.t has `fun:  (Tesla.Env.t, Tesla.Env.stack -> Tesla.Env.t),` part, but the `fun` can be nil. I'll try to find a workaround.

**Comment by teamon** [comment]
Please check with current master (https://github.com/teamon/tesla/commit/8fb4acaa108990cdb962376fc60cc582f6b453b7)

**Comment by randycoulman** [comment]
@teamon Yes, this resolves the problem for me.  Thanks!  Please let me know when you've created a release with the fix.

Thanks again for a great project.  I love using Tesla!

**Comment by teamon** [comment]
Thanks! I plan to push a new release in next few days
