### ISSUE TITLE
Implement access for env

### ISSUE THREAD

**Issue by christhekeele** [teamon/tesla#134]
The Access docs instruct us that, unless we are creating a container type, we shouldn't implement the behaviour for structs. This is because structs are meant to define things with static properties and the Access protocol is intended to access things with dynamic properties.

However, since a `Tesla.Env` is often a gateway to a dynamic JSON response, it'd be kind of convenient to use Access on it––in particular the derived `get_in` stuff, ie:

```elixir
response = Some.API.Client.build
|> Some.API.Call.get("/widgets.json")
value = get_in(response.body, ["json", "deep", "value"])

# could be

value = Some.API.Client.build
|> Some.API.Call.get("/")
|> get_in(["body", "json", "deep", "value"])
```

On the other hand, pretty much only a JSON `body`, and possibly `headers`, would benefit from being accessed this way, so we have to ask ourselves if this use-case common enough, and the convenience added substantial enough, to merit implementing access?

**Comment by teamon** [comment]
With structs you can do:

```elixir
iex(7)> Client.get("http://httpbin.org/ip") |> get_in([Access.key!(:body), "origin"])
"x.x.x.x"
```

I'm not sure implementing Access protocol for Tesla.Env gives much, especially since you probably want to match on `%{status: 200, body: body}` or something like this anyway

**Comment by teamon** [comment]
@amatalai wdyt?

**Comment by amatalai** [comment]
I'm neither for nor against, but I don't see much value in it.

At the moment I would do it like this:
```
value = Some.API.Client.build
|> Some.API.Call.get("/")
|> Map.get(:body)
|> get_in(["json", "deep", "value"])
```

**Comment by teamon** [comment]
This won't break anything, so let's keep it open. It might be a "good first issue" :)

**Comment by teamon** [comment]
Given the new return values (ok/error tuples) in 1.0 this would be even less useful, closing.
