### ISSUE TITLE
Default Adapter

### ISSUE THREAD

**Issue by rawkode** [teamon/tesla#138]
I experience a lot of problems with the default adapter and would like to suggest switching the default to Hackey, as it seems to provide the most stable experience out the box.

**Comment by teamon** [comment]
Hi,

What issues are you experiencing? The advantage to having httpc as the default adapter is that it is build-in into OTP and does not require any additional dependencies.

**Comment by ourway** [comment]
Hackney is full of issues, timeouts, crashes, ...  IMHO the point of Tesla is to get rid of hackney.

**Comment by teamon** [comment]
The point of Tesla is not to get rid of hackney, nor any other http adapter. The point is to let the end use choose the adapter that suits best or write a custom one if needed.

**Comment by jtomaszewski** [comment]
@ourway What do you propose to use instead then?

**Comment by ourway** [comment]
@jtomaszewski Erlang' default httpc
