### ISSUE TITLE
How to delegate to Tesla's HTTP verbs

### ISSUE THREAD

**Issue by thehunmonkgroup** [teamon/tesla#146]
I'm writing a very simple wrapper for a JSON REST API, and using Tesla for the HTTP communication layer.

I'd like to be able to simply delegate my module's verbs (get, post, etc) to Tesla, as I see no sense in reinventing the wheel there, but I haven't found a way to do it yet.

The basic module setup is like this:

```elixir
defmodule DigitalOcean do
  @api_endpoint_default "https://api.digitalocean.com/v2"

  use Tesla

  plug Tesla.Middleware.BaseUrl, Application.get_env(:digitalocean, :api_endpoint, @api_endpoint_default)
  plug Tesla.Middleware.Headers, %{"Authorization" => "Bearer " <> Application.get_env(:digitalocean, :access_token)}
  plug Tesla.Middleware.JSON
end
```

I can't do this:

```elixir
def get(path) do
  get(path)
end
```

Because that's a namespace conflict.

So right now I've used the rather lame:

```elixir
def do_get(path) do
  get(path)
end
```

I tried to use ```defdelegate``` like this:

```elixir
defdelegate get(path), to: Tesla, as: :get
```

But that didn't include the plugs.

Is there some reasonable way to accomplish what I'm wanting?

**Comment by amatalai** [comment]
Hi, try
```
defdelegate get(path), to: DigitalOcean, as: :get
```
It should include plugs from DigitalOcean module

**Comment by thehunmonkgroup** [comment]
Oh, I didn't realize that, so much easier!

Thanks for your help, all good now.
