### ISSUE TITLE
setting optional custom values, while building a custom client, and access them later in requests, if possible?!

### ISSUE THREAD

**Issue by florinpatrascu** [teamon/tesla#154]
Hi there. 

With `Tesla.build_client/2`, how can I set a custom options value and retrieve it later, in a request: post/get/etc. **before** running the request? I am new to Tesla, and most probably I am missing an obvious solution. What I am doing right now:

- in a custom function, I am building a new client, like this:

```elixir
Tesla.build_client(
      [
        {Tesla.Middleware.BaseUrl, endpoint_url},
        {Tesla.Middleware.Headers, %{"Authorization" => token}},
        {Tesla.Middleware.Opts, [foo: "bar"]}
      ], []
```

- then I would like to use the value of `:foo`, in a say: `POST`, request, as a query value?! Something like:

```elixir
get( client,
       "/some_path",
       query: [
          q: "bar" # < this is where I would need to access the `client`'s opts, if possible?
       ])
```
am I thinking this wrong?

Thank you!

**Comment by teamon** [comment]
The `Opts` middleware was initially meant to be used as a way to provide some specific options for adapters (afair adapters are the only ones using `env.opts`) but `opts` field itself is used by e.g. `Rels` middleware.

Having said that, I'm not sure what are you trying to achieve - the `Opts` middleware will be executed as part of the request pipeline, which is not started until one of the get/post/etc is called, in other words there is no `client.opts`, only `env.opts` and client is really just a wrapper around list of middleware to be applied.

**Comment by florinpatrascu** [comment]
No problem, I'll find a workaround. Thanks again, for your support!
