### ISSUE TITLE
Global middleware

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#167]
Super useful, especially when using existing libraries like [elixir-google-api](https://github.com/GoogleCloudPlatform/elixir-google-api)

```ex
# global for all tesla-based clients
config :tesla, middleware: [MySuperMetrics]

# for specific client
config :tesla, GoogleApi.Datastore.V1.Connection, middleware: [MySuperMetrics]

# inserting middleware before/after stack
config :tesla, middleware: [
  pre: [ModuleA], 
  post: [ModuleB]
]
```

**Comment by chulkilee** [comment]
If the client module has a list of middleware (inside module or using `build_client`) - then at which position this "global" middleware put in?

**Comment by teamon** [comment]
This is a good question to which I'm not sure about the answer yet. 
Right now it is:

```ex
stack = client.pre ++ module.__middleware__ ++ client.post ++ adapter
```
(see https://github.com/teamon/tesla/blob/master/lib/tesla.ex#L118)

**Comment by teamon** [comment]
Adding custom middleware is possible with custom client, I no longer see much gain with global middleware.
