### ISSUE TITLE
Configure Adapter Per Request

### ISSUE THREAD

**Issue by rawkode** [teamon/tesla#178]
Hi,

Is it possible to configured the adapter during `Tesla.request` ?

**Comment by teamon** [comment]
You can use `Tesla.build_adapter/1` to add a custom adapter to client and call an existing adapter inside:

```
client = Tesla.build_adapter(fn env ->
  Tesla.Adapter.Hackney.call(env, [])
end)

Tesla.request(client, ...)
```

**Comment by rawkode** [comment]
Thanks for responding, @teamon; appreciated.
