### ISSUE TITLE
Query parameters seem to get concatenated.

### ISSUE THREAD

**Issue by tchoutri** [teamon/tesla#183]
Hi @teamon! I'm using Tesla to make a GET request with the following list of query parameters:
```
[antidimensions: ["dim", "city"], case_sensitive: false, dimensions: [], keep_accents: false, keep_quotes: false, sentence: "221 baker st london nw1 6xe uk", timezone: ""]
```
However, accoding to the DebugLogger Middleware, the list's elements get concatenated, to give:

```
00:23:39.775 [debug] >  Query Param 'antidimensions': 'dimcity'
```

So obviously there's something fishy to all that. Is it solvable from my side?

Thanks for your work, btw :)

**Comment by amatalai** [comment]
That's because `"#{["a", "b"]}"` ends as `"ab"`

Possible solution #186

**Comment by teamon** [comment]
@tchoutri Please check with https://requestb.in/ what is really sent since DebugLogger seems to be buggy with query params. You can try tesla master since #186 is already merged.

**Comment by tchoutri** [comment]
@teamon 
I ended up with a workaround by duplicating the key in the request such as `?foo=bar1&foo=bar2` instead of just `?foo=[bar1,bar2]`.
Not my best hack but it does work well, actually (and the API I'm hitting seems happy with it)
Thanks for your answers, I'll keep them close for when I need them

**Comment by teamon** [comment]
TBH I don't recognise any API using this format: `?foo=[bar1,bar2]`. The HTTP specs do allow multiple values for the same param like `?foo=bar1&foo=bar2`, most often used in the form of `?foo[]=bar1&foo[]=bar2` to make it clear that said param is expected to be an array. 

In fact, this is exactly what `Tesla.build_url` does:

```ex
iex> Tesla.build_url("example.com", foo: ["bar1", "bar2"]) |> URI.decode
"example.com?foo[]=bar1&foo[]=bar2"
```
