### ISSUE TITLE
Can't seem to post to a url with data. Any pointers?

### ISSUE THREAD

**Issue by sergiotapia** [teamon/tesla#188]
My module looks like this:

```
defmodule MyApp.ExampleWrapper do
  use Tesla

  plug(Tesla.Middleware.BaseUrl, "https://api.someapp.com")
  plug(Tesla.Middleware.Headers, %{"Content-Type" => "application/x-www-form-urlencoded"})

  def token_client do
    Tesla.build_client([
      {Tesla.Middleware.Headers, %{"Authorization" => "Bearer " <> token()}}
    ])
  end

  def http_auth_client do
    Tesla.build_client([
      {Tesla.Middleware.BasicAuth,
       %{username: System.get_env("APP_KEY"), password: System.get_env("APP_SECRET")}}
    ])
  end

  def fetch_new_token do
    post(http_auth_client(), "/someurl/token", %{grant_type: "client_credentials"})
    |> IO.inspect()
  end
end
```

But this post errors out with this message:

```
** (FunctionClauseError) no function clause matching in :httpc.request/5

     The following arguments were given to :httpc.request/5:

         # 1
         :post

         # 2
         {'https://api.app.com/someurl/token', [{'authorization', 'Basic VALUESHERE'}, {'content-type', 'application/x-www-form-urlencoded'}], 'application/x-www-form-urlencoded', %{grant_type: "client_credentials"}}

         # 3
         [autoredirect: false]

         # 4
         []

         # 5
         :default
```

I'm not sure what I'm doing wrong, my code is small enough that I don't see where I messed up. I'm just trying to POST to that url with the `grant_type: client_credentials` param. 

Appreciate the help, I'll also update the readme with things I missed.

**Comment by teamon** [comment]
Where do you pasa the params? The post(...) call seem to be missing params.

**Comment by sergiotapia** [comment]
Sorry @teamon - edited my initial code sample. I'm passing it as the third parameter of my call to Tesla's `post/3`.

**Comment by teamon** [comment]
You need to use proper body encoder, like [`Tesla.Middleware.FormUrlencoded`](https://hexdocs.pm/tesla/Tesla.Middleware.FormUrlencoded.html)

**Comment by teamon** [comment]
@sergiotapia Closing this one, feel free to reopen.

**Comment by garthk** [comment]
For anyone getting here by searching on `FunctionClauseError` and `no function clause matching in :httpc.request/5`, check to see if you overrode `method` in `%Env` with `"POST"` instead of `:post`.
