### ISSUE TITLE
Cache middleware

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#189]
I think we should have a decent HTTP cache middleware (like faraday-http-cache) with pluggable backend (a simple interface of get/put) while handling all of the HTTP cache stuff

**Comment by chevinbrown** [comment]
@teamon you have an idea of implementation details?

**Comment by teamon** [comment]
There are many options, from super simple like "cache all GET for X seconds in ets" to full like [faraday-http-cache](https://github.com/plataformatec/faraday-http-cache)

Here is very old take on it (with old tesla) - https://gist.github.com/teamon/696232ca6e5a2955052914605c4e05c0#file-more_middlewares-ex-L1 baced by file (don't do it ;))

**Comment by chulkilee** [comment]
I like having "official" middleware for general use case, but I'm not sure it's a good idea to add all of them into the main package.

**Comment by teamon** [comment]
Let's continue in #264
