### ISSUE TITLE
Can not pass query params to url in GET.

### ISSUE THREAD

**Issue by kunashir** [teamon/tesla#190]
I try to use Tesla and my first attempt was simply  get request with query params.
I used example from the documentation but the url was without query.
I've tried code from the documentation but it also doesn't work properly (or maybe I do not understand something):
```elixir
 res = Tesla.get("http://httpbin.org/get", query: [a: 1, b: "foo"])
%Tesla.Env{
  __client__: nil,
  __module__: Tesla,
  body: "{\n  \"args\": {\n    \"a\": \"1\", \n    \"b\": \"foo\"\n  }, \n  \"headers\": {\n    \"Connection\": \"close\", \n    \"Host\": \"httpbin.org\"\n  }, \n  \"origin\": \"178.234.238.108\", \n  \"url\": \"http://httpbin.org/get?a=1&b=foo\"\n}\n",
  headers: %{
    "access-control-allow-credentials" => "true",
    "access-control-allow-origin" => "*",
    "connection" => "keep-alive",
    "content-length" => "203",
    "content-type" => "application/json",
    "date" => "Fri, 16 Mar 2018 06:00:31 GMT",
    "server" => "meinheld/0.6.1",
    "via" => "1.1 vegur",
    "x-powered-by" => "Flask",
    "x-processed-time" => "0"
  },
  method: :get,
  opts: [],
  query: [a: 1, b: "foo"],
  status: 200,
  url: "http://httpbin.org/get"
}
iex(2)> res.url
"http://httpbin.org/get"
```

Version of  Tesla: "0.10.0"

**Comment by teamon** [comment]
As you can see in the body the query params are passed correctly, they are just not appended to the url. (See #139 for the other side of this issue)

**Comment by kunashir** [comment]
I'm sorry but I can't understand what is problem with append query to a url.
Must I make url with query params manually?

**Comment by teamon** [comment]
> Must I make url with query params manually?
No
> Also It makes some examples in documentation are wrong?
No

The query params are passed correctly, please examine the response body in your first example.

**Comment by kunashir** [comment]
But how about this:
```elixir
response = Tesla.get("http://httpbin.org/get", query: [a: 1, b: "foo"])
response.url     # => "http://httpbin.org/get?a=1&b=foo"
```
I'd show in the first post that it is not.

**Comment by teamon** [comment]
As I said, it works correctly but the query params are not appended to url field.

```ex
Tesla.get("https://requestb.in/1dr7o931", query: [a: 1, b: 2])
```

<img width="320" alt="cloudapp annotation 2018-03-19 at 9 24 06 am png" src="https://user-images.githubusercontent.com/8083/37584857-56a521d0-2b57-11e8-834b-11b069ab63e8.png">

**Comment by teamon** [comment]
I'm closing this one. @kunashir feel free to comment if you have any more questions.
