### ISSUE TITLE
Mock helpers

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#194]
Currently to mock a JSON response one has to write:

```ex
Tesla.Mock.mock fn env ->
  {:ok, %Tesla.Env{status: 200, body: ~s|{"ok": true}|, headers: [{"content-type", "application/json}]}
end
```

Since this (and some other) cases are very common it would be useful to have:

```ex
Tesla.Mock.mock fn env ->
  json(%{"ok" => true})
end
```

or

```ex
Tesla.Mock.mock fn env ->
  json(%{"ok" => true}, status: 201)
end
```

Also, returning simple `{200, [], "hello"}` tuple instead of full `Tesla.Env` might be handy.

Right now the proposal is to have:

- [x] Handle other return types with the following rules:
  - [x] `Tesla.Env => {:ok, Tesla.Env}`
  - [x] `{status, headers, body} => {:ok, Tesla.Env{...}}`
  - [x] `other => {:error, other}`
- [x] Add utility functions:
  - [x] `json(body, opts \\ []) :: Tesla.Env` (status defaults to 200, set proper content type header)
  - [x] `text(body, opts \\ []) :: Tesla.Env` (status defaults to 200, set proper content type header)
- [x] Provide JSON engine configuration (`config :tesla, Tesla.Mock, json_engine: Jason`)
- [x] Update REAMDE (with `import Tesla.Mock.Helpers` line)

**Comment by florinpatrascu** [comment]
hi @teamon - can I configure a different json engine, programmatically? I am porting my projects to 1.0.0-beta.1, but some of them have "hard" dependencies on Poison, so I have to stick with the latter for time being. ty!

**Comment by teamon** [comment]
```
config :tesla, Tesla.Mock, json_engine: Poison
```

**Comment by florinpatrascu** [comment]
hah, I was thrown on a wrong path being mislead by the `Tesla.Mock`, thinking you're planning to use it for tests (internally) only :) Thank you!
