### ISSUE TITLE
Testing requests

### ISSUE THREAD

**Issue by wilbertom** [teamon/tesla#195]
Hello, I'm looking for a way to test against the request sent by a module. My initial intuition was to capture the request during the mock but I'm having trouble doing it in a clean way.

```elixir
defmodule ApiTest do      
  use ExUnit.Case                  

  setup do                     
    Tesla.Mock.mock fn             
      %{method: :get} = env ->     
        # capture request env here              
        %Tesla.Env{}                         
    end          

    {:ok}        
  end            

  test "issue some request here" do                   
    Api.get("")           
    
    assert request.query == [query: "hello world", token: "12345"]
  end            
end
```

My second intuition is to create a middleware that pushes the untouched request at the beginning of the pipeline into somewhere I can read from in the test.

I tried using a global variable but couldn't figure out how to do that in elixir but, I didn't spend too much time toying with that idea because then tests would have to always run serially.

**Comment by teamon** [comment]
You can return the request in mock (fn env -> env end) but it will be processed by middleware stack as response.
The alternative is to send a message to current process - https://twitter.com/iteamon/status/851375743284244481?s=20

**Comment by teamon** [comment]
In this case you don’t even need to register the process since Tesla mock runs in the same process so just

# in mock
send self(), env

# in test
assert_receive ...

**Comment by wilbertom** [comment]
Thank you very much @teamon, I went with sending a message to self.
