### ISSUE TITLE
DecodeRels middleware does not work with httpc

### ISSUE THREAD

**Issue by thbar** [teamon/tesla#20]
First, thanks for your great library ; it's a great pleasure to use :smile:!

Today I tried to rely on the `DecodeRels` middleware while working on paginated ETL, but it failed to decode the `Link` header.

I had a closer look, and I believe that the culprit is that `httpc` returns lower-case headers all the time for me (e.g. `link`), while headers are actually returned as `Link`, and the middleware expects `Link` ([code](https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/core.ex#L98)).

Example with curl (with other headers):

```
$ curl -I http://httpbin.org/ip
# SNIP
Content-Type: application/json
Content-Length: 33
```

And with `httpc`:

```
iex(3)> :httpc.request(:get, {"http://httpbin.org/ip" |> to_char_list ,[]}, [], [])
{:ok,
 {{'HTTP/1.1', 200, 'OK'},
  [{'connection', 'keep-alive'}, {'date', 'Fri, 09 Sep 2016 09:18:42 GMT'},
   {'server', 'nginx'}, {'content-length', '33'},
   {'content-type', 'application/json'},
# SNIP
  '{\n  "origin": "80.215.228.205"\n}\n'}}
```

I haven't tested other adapters yet.

I presume being case insensitive on the `Link` look-up in the middleware could be the way to go for a first step. Another possibility would be to allow configuration of the key name (but this feels more bloaty).

What do you think?

Thanks!

**Comment by thbar** [comment]
For now, I've implemented a hot-fix that works for me here https://github.com/thbar/tesla/commit/476b4eda9d826a4aa0b20fded93c8d5ebc1b5d35.

**Comment by princemaple** [comment]
I think a better solution is to have the adapters keep some internal static configuration, and let the middlewares query the adapter, if it needs to run differently with different adapters. @teamon

**Comment by teamon** [comment]
@thbar Thanks for the report! All headers leaving adapter are already normalized to be in form of `map(lowercase_string => string)` so this was definitely a bug in DecodeRels middleware.

@princemaple Middlewares should not depend on adapter - I believe if adapter does not support something it should be its responsibility to raise a proper exception

**Comment by thbar** [comment]
@teamon you welcome - and thanks for the quick fix! I had no idea this was normalized this way - thanks for the note!
