### ISSUE TITLE
camelCase header name

### ISSUE THREAD

**Issue by quatermain** [teamon/tesla#202]
Hello,

I have to send header in camelCase format, like this:
`apiKey: token`
but right now it's not possible because Tesla or adapters downcase it and it shows on the server like `apikey`. 

I use it like this:
`plug(Tesla.Middleware.Headers, [{"apiKey", api_key()}])`

Is it possible to send it in my format somehow please?

**Comment by chulkilee** [comment]
I think this is not happening at 1.x, since `Normalize` middleware is gone. 

On 0.x: see https://github.com/teamon/tesla/blob/v0.10.0/lib/tesla/middleware/core.ex#L27

**Comment by quatermain** [comment]
I changed adapter ```adapter(Tesla.Adapter.Hackney)``` and it works

**Comment by chulkilee** [comment]
It is `httpc` does the conversion. See https://github.com/erlang/otp/blob/OTP-20.3.6/lib/inets/src/http_client/httpc.erl#L504

```erlang
 NewHeaders0 = [{http_util:to_lower(Key), Val} || {Key, Val} <- Headers0],
```

**Comment by chulkilee** [comment]
@teamon could you add `httpc` label here? This is httpc specific issue. Also it would be nice if the title is updated as well...
