### ISSUE TITLE
httpc - empty content-type header on delete without body

### ISSUE THREAD

**Issue by chulkilee** [teamon/tesla#205]
#147 and its workaround (https://github.com/teamon/tesla/commit/63363f16d5d78141477672d375442edf29d902d3) fixes run time error, but still httpc passes empty `Content-Type` header (instead of omitting `Content-Type` header completely), and servers may not accept such requests.

httpc is fixed but it's only in 21, which elixir does not support yet.

- https://bugs.erlang.org/browse/ERL-536
- https://github.com/erlang/otp/commit/fd2af907bc854e5dc92fbd71efdab096be572573

Is it ever possible to workaround it from Tesla?

**Comment by teamon** [comment]
Unfortunately I don't think we can do anything about it since this happens on the httpc level :|

**Comment by chulkilee** [comment]
That was my guess :(

There are several adaptor-specific issues (e.g. hackney timeout). What about listing them somewhere? Wiki page or README or adaptor module doc..

**Comment by teamon** [comment]
This is now fixed in OTP 21.
