### ISSUE TITLE
Custom Content-Type for JSON Middleware 

### ISSUE THREAD

**Issue by jcsrb** [teamon/tesla#212]
The json middleware always adds `application/json` as content type [here](https://github.com/teamon/tesla/blob/5382b7ad60bd8f1c306b9143217d250e0376397d/lib/tesla/middleware/json.ex#L64) 

Using `Tesla.Middleware.Headers` to set a custom content-type , and `Tesla.Middleware.JSON` results in duplicate `content-type` headers. 
```
[debug] 
>>> REQUEST >>>
(no query)
content-type: application/json
content-type: application/vnd.api+json
```
My use cases revolves around http://jsonapi.org/ which requires the use of the `application/vnd.api+json` content-type.

with the `decode_content_types` option this middleware is open that format on the decode side, but not on the encode side of things

rather then removing `content-type: application/json` and then adding `content-type: application/vnd.api+json` in an extra step the JSON  middleware could accept an `encode_content_type` and set that as a content-type header 

would such a PR be welcome?

**Comment by teamon** [comment]
Yes! I makes sense to have `encode_content_type` 👍

**Comment by jcsrb** [comment]
closing issue as PR was merged, thanks
