### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by yanshiyason** [teamon/tesla#217]
Hi there,

I was wondering if it's possible to use a proxy with Tesla.
Something like this for instance: <https://www.rubydoc.info/gems/mechanize/Mechanize%2FHTTP%2FAgent%3Aset_proxy>.

**Comment by yanshiyason** [comment]
After a bit more research, I guess the lower level HTTP library (`httpc` in this case) should be able to take care of that..

Any idea on how to pass that configuration down to `httpc`?

... will do a bit more research

**Comment by yanshiyason** [comment]
Looking at the options for `httpc` <http://erlang.org/doc/man/httpc.html>
```
Options = [Option]
```

I give a list of options

```
Option = {proxy, {Proxy, NoProxy}} | ...
```
The option for proxy is the `poxy` symbol followed by config tuple.

```
Proxy = {Hostname, Port}
```

Proxy is a tuple with hostname(`string`) and port(`int`)
```
Hostname = string() (Example: "localhost" or "foo.bar.se")
Port = integer() (Example: 8080)
```
Then a list of `NoProxy` data types
```
NoProxy = [NoProxyDesc]
NoProxyDesc = DomainDesc | HostName | IPDesc

DomainDesc = "*.Domain" (Example: "*.ericsson.se")
IpDesc = string() (Example: "134.138")
```

Meaning that if I understood that right, the following should work?

```
plug Tesla.Middleware.Opts, [
    {:proxy, { "https://myproxy.com", 1234}, []}
]
```

**Comment by mpinkston** [comment]
It is possible, though each adapter handles proxies a bit differently.

In the case of httpc, I might be wrong, but I don't believe it's possible to define a proxy per-request, rather it has to be set using `:httpc.set_options(...)` before the request is made. Unfortunately, that means all requests will then use that proxy.

Example. 
```
iex> :httpc.set_options([https_proxy: {{'133.18.173.18', 60088}, []}])
:ok
iex> Tesla.get!("https://api.ipify.org").body
"133.18.173.18"
```

If you would like to define the proxy directly in the request options, I'd recommend using a different adapter like Hackney by specifying that in your config file:
```
config :tesla, adapter: Tesla.Adapter.Hackney
```

Then you can tell Tesla to pass the proxy options along to the adapter using the `adapter` keyword in opts:
```
iex> Tesla.get!("https://api.ipify.org", opts: [adapter: [proxy: {'133.18.173.18', 60088}]]).body
"133.18.173.18"
```

You could alternatively use the Opts middleware to configure the proxy as well
```
iex> cli = Tesla.build_client([{Tesla.Middleware.Opts, adapter: [proxy: {'133.18.173.18', 60088}]}])
iex> Tesla.get!(cli, "https://api.ipify.org").body
"133.18.173.18"
```

**Comment by yanshiyason** [comment]
@mpinkston Wonderful! Thank you so much for leading me in the right direction!
