### ISSUE TITLE
Improve documentation around adapters and custom adapters

### ISSUE THREAD

**Issue by josevalim** [teamon/tesla#218]
Hi everyone,

First of all, thanks for Tesla!

I would like to request the documentation to be improved around how to use adapters, how to write adapters and how to configure existing ones. Here are more specific points:

  * I couldn't find documentation on how to change adapters where I'd expect this information to be available. The only place I found it was on the README under the testing section.

  * The `Tesla` module has a `build_adapter` function but it has no documentation. It is unclear if it is private or public or how to invoke it without checking the source (there are other `build_*` functions with the same issue).

  * It seems to be possible to pass options to adapters. This is briefly mentioned in `Tesla.request/2` but there are no actual examples. When looking at the adapter modules themselves, they don't mention which options they accept. I would recommend doing something [similar to Plug](https://hexdocs.pm/plug/Plug.Adapters.Cowboy.html), where we list the main options and give a reference to more information.

  * Generally speaking, it would be nice if each adapter linked to their respective docs and provide brief information on the pros and cons. Adapters like Hackney should mention if they are using the default pool or not and similar information, to make customization more straight-forward. HTTP clients are a bit chaotic on the Elixir community right now. Tesla is attempting to solve some of those issues by making them replaceable, therefore it should provide more information on replaceability.

  * There is no information on writing adapters. `Tesla.Adapter` does define a callback but it doesn't document the callback. It should be mentioned what they receive, what they are expected to do and what they return (apparently a Tesla.Env with status, headers and body set).

  * `Tesla.Env` does not document any of its fields. This is important for users, middleware writers, and adapter authors. I would also document that the same `Tesla.Env` is used for requests and responses and fields like `headers` and `body` serve a dual purpose. This can catch some people off guard.

I would also suggest to use the [ExDoc grouping functionality](https://github.com/elixir-plug/plug/blob/master/mix.exs#L65). as you can see [in the Plug sidebar](https://hexdocs.pm/plug/), as I believe it makes the documentation easier to explore. Although I understand not everyone prefers this style.

Thanks for reading!

**Comment by teamon** [comment]
Quick reply:
1. https://github.com/teamon/tesla/wiki/0.x-to-1.0-Migration-Guide#adapter-options-need-to-be-wrapped-in-adapter-key
2. https://github.com/teamon/tesla/issues/151

**Comment by baldmountain** [comment]
Thanks Tymon,

That is just what I was looking for.

**Comment by teamon** [comment]
[copy from #240, let's continue here]

Currently adapter interface is weakly typed - the options passed for each middleware are different and the error return values are unknown (`{:error, any}`). 

To-do list:
- [x] ~~Define common set of error return values~~ - quite impossible
- [ ] Document adapter-specific options (how to use, link to source, link to labeled issues, etc.)
  - [ ] Documentation for httpc
  - [ ] Documentation for hackney
  - [ ] Documentation for ibrowse
