### ISSUE TITLE
Allow the adapter to be configured explicitly at runtime

### ISSUE THREAD

**Issue by josevalim** [teamon/tesla#219]
From my understanding of the code, the adapter today can only be configured at compile time or globally (via the app environment).

I would like to propose the adapter to be configured at runtime. Maybe a field on Tesla.Env or as an option. Since libraries may be using Tesla to provide a wrapper on a client, such as the GoogleCloudPlatform, it is important the adapter can be configured at runtime without a need to force recompilation of those libraries.

Thank you!

**Comment by teamon** [comment]
Adapter can be configured in few ways: https://github.com/teamon/tesla/blob/f0efd404b6225e55204e4e694a938d80a68d8904/lib/tesla.ex#L123-L129

This translates to the following order/fallbacks
```elixir
# 1. Get adapter via application config
config :tesla, SomeThirdPartyClient, adapter: AdapterOfMyChoice

# 2. Use the hardcoded adapter (inside module)
adapter SomeAdapter

# 3. Get global adapter via application config
config :tesla, adapter: AdapterOfMyChoice

# 4. Use default
Tesla.Adapter.Httpc
```

Configuring 3rd party clients is... tricky. I am not super happy with the current solution for adapters. I've been also discussing the introduction of global middleware configured via Application env versus just using a custom `Tesla.Client` that already can provide similar features.

If you have any good (or bad) suggestions, I'm all ears.

**Comment by josevalim** [comment]
The problem is that the suggestions above are all compile time or global. I would rely refrain from adding any global or compile time configuration. Global configuration can cause race conditions and makes it impossible to configure the client on per VM process. Compile time configuration means that the only way to configure a third party library is by changing the `config/config.exs` and then erasing its current build in the proper environment (or calling `mix deps.clean google_pub_sub_api`), which is confusing and generally a poor experience.

There is no reason for configuring 3rd party clients to be tricky. If all of the behaviour is at runtime, and you already provide a `Tesla.build_client` that works at runtime, any runtime configuration can be done by building a list of arguments given to `build_client`. If the adapter is an option on Tesla.Env or somewhere that exists at runtime, you could even have a middleware that sets the adapter. What makes 3rd party clients behaviour tricky is exactly compile/global behaviour, so adding more is bound to make the problem worse. :)

**Comment by teamon** [comment]
You *can* have per-client configuration, using undocumented `Tesla.build_adapter/1` that hacks the system by injecting malicious middleware that instead of calling `Tesla.run(env, next)` as every middleware should calls the given adapter directly instead. 💥 

I believe that moving away from macro-based module-bound code of `specific_module(optional_client, request_spec)` into `generic_tesla(client_with_all_config, request_spec)` is the way to go. Then, if only 3rd party libraries stick to using `Tesla.Client` instead of custom one you'd get full flexibility.

**Comment by teamon** [comment]
We can do it now with [`Tesla.client/2`](https://hexdocs.pm/tesla/Tesla.html#client/2)
