### ISSUE TITLE
Are Client side certificates supported?

### ISSUE THREAD

**Issue by favetelinguis** [teamon/tesla#223]
Im trying to port some code from python to Elixir, Tesla looks like a very nice option. However i need client certificates. Currently im using the solution described in the link below under the headline Client side certificates. 
http://docs.python-requests.org/en/master/user/advanced/

Is there something similar in Tesla for this?

**Comment by chulkilee** [comment]
It depends on actual http library.

[httpc doc](http://erlang.org/doc/man/httpc.html) and [hackney doc](https://hexdocs.pm/hackney/) both mention erlang ssl option, which can include client cert (see [ssl doc](http://erlang.org/doc/man/ssl.html))

It would be nice if tesla doc has examples for this :)

**Comment by favetelinguis** [comment]
Im using httpc atm, how can I actually provide the ssl options? Does this not have to be supported in the adapter for me to be able to do it?

**Comment by chulkilee** [comment]
You can pass any option down to your adapter.

Try something like this:

```elixir
MyClient.get("/", opts: [adapter: [ssl: [...]]])
```

For actual ssl option, check out https://elixirforum.com/t/using-client-certificates-from-a-string-with-httposion/8631

**Comment by teamon** [comment]
I agree it should be documented.
