### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by tielur** [teamon/tesla#224]
I'm curious where the name `tesla` came from for an HTTP Library? I found it confusing only because the car company Tesla has an API that I was expecting this library might be related to.

I'm curious about story behind the name Tesla for an HTTP Library.

**Comment by amatalai** [comment]
I guess https://en.wikipedia.org/wiki/Nikola_Tesla

Similar http lib written in ruby is called after another scientist https://en.wikipedia.org/wiki/Michael_Faraday

**Comment by teamon** [comment]
Exactly. I was missing a lib like ruby’s faraday and went with another scientist for the name.

**Comment by mushfick** [comment]
I think it's a great name @teamon.

**Comment by chulkilee** [comment]
BTW I believe the name `faraday` of [lostisland/faraday](https://github.com/lostisland/faraday) came from a character of *Lost* TV series, not the scientist.
