### ISSUE TITLE
Question about Tesla.post function

### ISSUE THREAD

**Issue by wlminimal** [teamon/tesla#226]
I am trying to do post request to this url
https://api-ssl.bitly.com/v4/shorten
with [long_url: "http://www.google.com"]
In doc it says **post(client, url, body, opts)**
so I tried Tesla(client, "https://api-ssl.bitly.com/v4/shorten",  "", [long_url: "http://www.google.com"])
I don't know what to put in body argument, so I tried with empty  string like ""
and as I expected it didn't work.
what should I put in body argument?

**Comment by chulkilee** [comment]
Are you using [this api](https://dev.bitly.com/v4/#operation/createBitlink)? The doc says body is in json.

```elixir
access_token = "foo"

client = Tesla.build_client([
  {Tesla.Middleware.BaseUrl, "https://api-ssl.bitly.com"},
  {Tesla.Middleware.Headers, [{"Authorization", "Bearer #{access_token}"}]},
  Tesla.Middleware.JSON
])

{:ok, resp} = Tesla.post(client, "/v4/shorten", %{long_url: "http://www.google.com"})

resp.body
# it's a Map
```

**Comment by teamon** [comment]
@wlminimal You need to include more information, we are not oracles. 

If you want to make a HTTP request you need to know at least the method and URL. If this is a POST(or PUT) you need to know the format of the body (content-type). Most popular ones are JSON and form/url-encoded - there are specific tesla middlewares for these. 
Please read the docs what is the `opts` argument.

I'm closing this issue right now, but please do comment if you have more details (and more specific issue), I'm happy to open it then.
