### ISSUE TITLE
JSON middleware should skip empty body

### ISSUE THREAD

**Issue by cs-victor-nascimento** [teamon/tesla#23]
I am building a client that has HEAD methods which return empty bodies. The `""` body should not pass as a decodable [here](https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/json.ex#L54).

When I change it to: `def decodable_body?(env), do: (is_binary(env.body) && env.body != "") || is_list(env.body)` it works as expected. 

I would propose a PR but it is really a small change...

Thanks in advance for your work! If possible, could you release a new version with this fix?

**Comment by teamon** [comment]
@cs-victor-nascimento does those HEAD requests have `Content-Type: application/json` ?

**Comment by cs-victor-nascimento** [comment]
Yep they do :)

Thanks for the quick fix! I've forgotten the list case...
