### ISSUE TITLE
Config Option or Middleware options 

### ISSUE THREAD

**Issue by collegeimprovements** [teamon/tesla#232]
Hi Teamon,
Thanks a lot for making Tesla. It's amazing.

With `ex_aws` we can do like the following via config file:  

```elixir
config :ex_aws, :hackney_opts,
  proxy: System.get_env("PROXY"),
  follow_redirect: true,
  ssl_options: [{:versions, [:"tlsv1.2"]}],
  recv_timeout: 30_000,
  insecure: true
```

Is there any way to do the same with `Tesla` ? 
Is it possible to do same in `Tesla`! 
Even better, is it possible to do same in some `middleware` ?

**Comment by teamon** [comment]
Assuming you are asking about "how to set hackney adapter option using config" you can do it with:

```elixir
config :tesla, :adapter, {Tesla.Adapter.Hackney, [...options...]}
```

**Comment by collegeimprovements** [comment]
Is it possible to set `proxy` for one Middleware and not to set `proxy` for another Middleware ?

**Comment by teamon** [comment]
I don't think I fully understand what are you trying to achieve here. Can you explain a bit more?

**Comment by teamon** [comment]
Thanks. 

The easiest way to do it is to set the adapter inline:

```elixir
defmodule ClientA do
  use Tesla
  # ...
  adapter Tesla.Adapter.Hackney, proxy: "proxy-a"
end

defmodule ClientB do
  use Tesla
  # ...
  adapter Tesla.Adapter.Hackney, proxy: "proxy-b"
end
```

You can also do it via config:

```elixir
# config/prod.exs
config :tesla, MyApp.ClientA, adapter: {Tesla.Adapter.Hackney, [proxy: "proxy-a"]}
config :tesla, MyApp.ClientB, adapter: {Tesla.Adapter.Hackney, [proxy: "proxy-b"]}
```

**Comment by collegeimprovements** [comment]
Thanks a lot @teamon, that solves it :)
