### ISSUE TITLE
httpc and no certificate checking by default

### ISSUE THREAD

**Issue by lau** [teamon/tesla#235]
The default adapter is httpc, which does not check certificates when using HTTPS. This seems like an unsafe default. Many people will probably use the default and use it to communicate with APIs. Perhaps with sensitive data.

I tried to use Tesla to make requests using hackney as the adapter, but from the README and docs it was not clear to me how to use Hackney by passing arguments to e.g. the `Tesla.get` function. Even when passing the adapter module as an argument and using the "use" macro, I found that httpc was still used.

I suggest making hackney the default adapter. Or another adapter that checks certificates. Either way making it clear in the readme, examples, documentation how to use a different adapter. And if httpc is still used as the default there could be warnings about not using httpc for purposes where HTTPS security is important.

**Comment by teamon** [comment]
If you want to use `Tesla.get()` with custom adapter see https://github.com/teamon/tesla/issues/219#issuecomment-403279451

I agree there should be a clear note about HTTPS.

**Comment by teamon** [comment]
Added to README
