### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by mikeroosa** [teamon/tesla#248]
When I submit an api request to the "MyFantasyLeague" api, I have to pass a username and password in the query string. The server responds with a cookie I can use for subsequent requests.

I can seem to get the value of the cookie in tesla. Am I missing something?

It works fine in Postman and recognizes the cookie.

The request is as follows: 
https://api.myfantasyleague.com/2018/login?USERNAME=myusername&PASSWORD=mypassword&JSON=1

I do get a 200 back, but don't see the cookie value anywhere.

The docs state for the API state:
If valid information is passed into the login program, the response will include a <status cookie_name="cookie_value"...>.
If invalid information is passed into the login program, it will respond with an <error... status message.

Any idea what I may be doing wrong?

**Comment by teamon** [comment]
@mikeroosa I don't understand what are you asking. 

Please provide the code samples you are using, the responses you receive, the things you've tried and what are you expecting.

**Comment by mikeroosa** [comment]
Sorry team. I found the issue. The API says it supports JSON and it does for every endpoint except the login! The login endpoint uses XML.
