### ISSUE TITLE
Alow setting adapter options at runtime

### ISSUE THREAD

**Issue by ConnorRigby** [teamon/tesla#250]
Some options to an adapter need to be changed/set at runtime. One use case of this is client side ssl certs. At compile time, you may not have access to the cert and key that will be used. (since it may be in an env var or something at runtime).

At least Hackney supports passing options per requrest. Not sure of other since i've not used them, but i suspect they support it as well. 

[the docs](https://hexdocs.pm/tesla/Tesla.html#get/3) suggest you can pass options into each of the http verb functions, but there is little to know documentation on what this argument is meant to be other than [`any`](https://hexdocs.pm/tesla/Tesla.Env.html#t:opts/0)

**Comment by teamon** [comment]
tl'dr

```elixir
MyClient.get("/", opts: [adapter: [recv_timeout: 30_000]])
```

If you want to use tesla's master you can check the new [`Tesla.client`](https://github.com/teamon/tesla/blob/master/lib/tesla.ex#L433-L475) function and build a client in runtime like:


```elixir
defmodule MyApi do
  def new(certs) do
    middleware = [...]
    adapter = {Tesla.Adapter.Hackney, [some_ssl_opts: cers]}
    Tesla.client(middleware, adapter)
  end
end
```

**Comment by ConnorRigby** [comment]
This worked great! thanks @teamon
