### ISSUE TITLE
Tesla.Env.url is not consistent using a builder vs no builder

### ISSUE THREAD

**Issue by tcoopman** [teamon/tesla#253]
This is from https://github.com/teamon/tesla/blob/master/lib/tesla/builder.ex#L27

> `:url`      - either full url e.g. "http://example.com/some/path" or just "/some/path" if using `Tesla.Middleware.BaseUrl`

But when you don't use a builder, `url` is always the full url, whether you use `Tesla.Middleware.BaseUrl` or not.

**Comment by tcoopman** [comment]
I think a good solution would be to add all the information in other field. For example add `host`, `path`, `scheme` (see https://hexdocs.pm/elixir/URI.html#types). Maybe even add a parsed uri field?

**Comment by teamon** [comment]
> But when you don't use a builder, url is always the full url, whether you use Tesla.Middleware.BaseUrl or not.

I don't understand this, can you explain a bit more?

**Comment by tcoopman** [comment]
Sure,

See these examples:

```elixir
defmodule Play1 do
  use Tesla

  plug(Tesla.Middleware.BaseUrl, "https://www.example.com")
  plug(Foobar, %{})
  
  def list_transactions(wristband) do
    get('/any/url')
  end
end

defmodule Play2 do
  def list_transactions(wristband) do
    Tesla.build_client([
      {Tesla.Middleware.Headers, [{"X-TENANT", "qa"}]},
      {Foobar, %{}}
    ])
    |> get("/any/url")
  end
end
```

With `Play1`, the middleware `Foobar` will get `https://www.example.com/any/url` in `env.url`. In `Play2` the url will be `/any/url`.

That's in the least surprising and it means that `Middleware`s that care about the url have to know if you're using a builder or not.

**Comment by teamon** [comment]
What is you use case for middleware that "cares about the url"? 

The URL should always be a URL, `Tesla.Middleware.BaseUrl` is a convenience middleware so you don't have to repeat the same host for every `get/post` etc. call. Your second example should include `... |> get("https://www.example.com/any/url")`

**Comment by tcoopman** [comment]
My use case for middleware that cares about the url: a middleware to do hmac authentication, like for http://s3.amazonaws.com/doc/s3-developer-guide/RESTAuthentication.html. The `canonicalizedResource` needs the path and query params (https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheCanonicalizedResourceElement)

I've made mistake in the example, edited it. It now also contains the `BaseUrl`, so they should be identical without doing `... |> get("https://www.example.com/any/url")

**Comment by teamon** [comment]
Please double check what you're doing, I would be very surprised if your example turned out to be true:

```elixir
defmodule Foobar do
  def call(env, next, _opts) do
    IO.inspect({:url, env.url})
    Tesla.run(env, next)
  end
end

defmodule X do
  use Tesla
  
  def list do
    client = Tesla.build_client([{Tesla.Middleware.BaseUrl, "http://example.com"},Foobar])
    get(client, "/some/path")
  end
end

X.list()
# {:url, "http://example.com/some/path"}
# => {:ok, ...}
```

**Comment by tcoopman** [comment]
You're partly right, it's not completely like I described it.
If the custom middleware is before the `BaseUrl`, the url only contains the path. If the custom middleware is after the `BaseUrl`, it contains the full url.

**Comment by teamon** [comment]
Yes, that’s the correct and the only logical behavior. That’s why BaseUrl is usually first and Logger is last.

What is the issue with that?

**Comment by teamon** [comment]
If that line was referring to `Tesla.Env#url` field then yes, it would depend on the context, but this is an option given to `request()` function, and there it can be one of the described two.
