### ISSUE TITLE
Mint adapter

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#282]
An adapter for [mint](https://github.com/ericmj/mint).

**Comment by doughsay** [comment]
Given the low-level nature of Mint, would it maybe make more sense to make a [mojito](https://github.com/appcues/mojito) adapter?  Just curious how this is going to play out with everything being so new.

**Comment by teamon** [comment]
I don't think adding one more layer would give a lot. Tesla adapters are quite low-level. For the same reasons there is no httpoison adapter, but there is one for hackney. However nothing is set in stone yet, it's hard to judge without actually trying to write the mint adapter. 

There is also a possibility that tesla's adapter API will have to be somehow expanded to give more control over that adapter settings. One of the reasons behind mint was to allow its users to define their own process/pool behaviour and I would like to embrace that, while keeping the nice & friendly API of tesla. So you can have readable API clients & high performance HTTP execution at the same time.

**Comment by amatalai** [comment]
>it's hard to judge without actually trying to write the mint adapter

I tried to write something over the weekend. 😄 

It's not finished yet, but I think that at least one additional process is needed for handling connections. Otherwise, it wouldn't reuse them and thus be rather useless compared to other adapters.

I'll try to make a PR in the next few days to discuss it further.

**Comment by keathley** [comment]
@amatalai Have you been able to take a look at this more? We'd like to move to mint ASAP so I'm happy to help with this if the code is available somewhere :+1:.

**Comment by amatalai** [comment]
@keathley Unfortunately not yet. I plan to go back to it during the weekend.

**Comment by keathley** [comment]
No worries. Wasn't trying to put pressure on you to work on it. I just didn't want to duplicate efforts :).

**Comment by RyanSiu1995** [comment]
Hi, I am dealing with this issue now. Will have a pull request as soon as possible!
Thank you!

**Comment by yordis** [comment]
@teamon I believe this is done

**Comment by teamon** [comment]
Yes!
