### ISSUE TITLE
How to disable request logging

### ISSUE THREAD

**Issue by jan0991** [teamon/tesla#283]
```
[info] [73, 110, 118, 97, 108, 105, 100, 32, 111, 112, 116, 105, 111, 110, 32, [123, ['proxy', 44, [123, ['"92.211.175.165"', 44, '13150'], 125]], 125], 32, 105, 103, 110, 111, 114, 101, 100, 32, 10]
```
I am using proxy with httpc and for every reuqest I see this. I tried implementing custom `Tesla.Middleware.RequestLogger` but it doesn't go away. I also tried setting `plug Tesla.Middleware.Logger, log_level: &my_log_level/1` to only errors but it doesn't work.

How can I disable request logging? Or set it to `:error` only?

**Comment by teamon** [comment]
Are you sure this comes from Tesla? Do you see it when you remove Tesla.Middleware.Logger?

**Comment by jan0991** [comment]
Thanks for getting back to me so fast. Yep it very likely wasn't tesla but httpc. It also didn't use the proxy properly. Replacing it with hackney fixed both issues.
