### ISSUE TITLE
Support gun as backend/adapter

### ISSUE THREAD

**Issue by NobbZ** [teamon/tesla#285]
* https://hex.pm/packages/gun

**Comment by teamon** [comment]
@NobbZ You are more than welcome to implement the adapter. 

I'm not using gun, please do not expect this to be implemented by me.

**Comment by NobbZ** [comment]
Currently I do not as well, but yesterday I was told it were the only one supporting HTTP2 out of the box.

This is the main reason why I'm asking for getting support into hackney.

**Comment by teamon** [comment]
There is also [mint](https://github.com/teamon/tesla/issues/282)

**Comment by teamon** [comment]
Closing in favour of https://github.com/teamon/tesla/pull/304
