### ISSUE TITLE
Seeing detailed request/response logging 

### ISSUE THREAD

**Issue by RafaelCamarda** [teamon/tesla#291]
Hey guys, is there any way to enable detailed request/response logging wihtout changing my entire app to `:debug`? I Would like to see request/response but using `:info` as log_level.

Is this only possible creating  Custom log formats ?

Thanks!

**Comment by teamon** [comment]
Currently there is no easy way to do this. 
What is the use case for this? Printing raw request/response in any other environment than development is a bad idea as you will leak all kinds of secrets, tokens, passwords from headers/body into logs.

**Comment by RafaelCamarda** [comment]
Ok, thanks for the answer. I'm closing this issue.
