### ISSUE TITLE
Support async requests using Digest Auth

### ISSUE THREAD

**Issue by adkron** [teamon/tesla#302]
I need to stream mjpg, and the only want to make that work is to have support for async. If we utilize the ability of hackney to make async requests, we would be able to support a lot of other use cases. I was trying to think of an elegant way to deal with the callbacks that would need to be in place. One thought I had is when passing async to the adapter that we make the value a function, or module, or MFA. The only strange thing with that is that it isn't a direct configuration of Hackney that we would be sending. The other idea that I had was to have a completely separate call for asynchronous requests.

**Comment by teamon** [comment]
Hi @adkron,

Could you maybe give some examples? I'm not 100% sure I understand what you mean.

**Comment by adkron** [comment]
This issue may only happen when using digest auth, but I am not in charge of the endpoint.

Let's say that you have a remote device, such as a camera, that streams mjpg. Streaming a never-ending request can be done with hackney using async.

Adding to that if the stream has digest auth, then setting the `async` flag for hackney creates a situation where the authorization never completes. In my investigation, I get an unauthorized, and then the other digest auth requests never happen.

I hope this helps.

**Comment by teamon** [comment]
I'm sorry, but I still don't understand what is the issue here, or what would you expect to happen?

It is impossible to even start thinking of this without any working examples.

**Comment by adkron** [comment]
I will work up an example this weekend and put all the information I can into it.

**Comment by adkron** [comment]
I found a public test server for digest auth so this didn't take the weekend. Pass is non-async and fail is async.

Code

~~~elixir
defmodule TeslaTest.Pass do
   use Tesla
   plug Tesla.Middleware.BaseUrl, "http://httpbin.org/"
   plug(Tesla.Middleware.DigestAuth, username: "user", password: "passwd")
   adapter(Tesla.Adapter.Hackney, async: false)

   def test do
     get("digest-auth/auth/user/passwd")
   end
end

defmodule TeslaTest.Fail do
  use Tesla
  plug Tesla.Middleware.BaseUrl, "http://httpbin.org/"
  plug(Tesla.Middleware.DigestAuth, username: "user", password: "passwd")
  adapter(Tesla.Adapter.Hackney, async: true)

  def test do
    get("digest-auth/auth/user/passwd")
  end
end
~~~

Output


~~~elixir
iex(21)> TeslaTest.Pass.test
{:ok,
 %Tesla.Env{
   __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
   __module__: TeslaTest.Pass,
   body: "{\n  \"authenticated\": true, \n  \"user\": \"user\"\n}\n",
   headers: [
     {"access-control-allow-credentials", "true"},
     {"access-control-allow-origin", "*"},
     {"content-type", "application/json"},
     {"date", "Fri, 31 May 2019 20:04:16 GMT"},
     {"referrer-policy", "no-referrer-when-downgrade"},
     {"server", "nginx"},
     {"set-cookie", "fake=fake_value; Path=/"},
     {"x-content-type-options", "nosniff"},
     {"x-frame-options", "DENY"},
     {"x-xss-protection", "1; mode=block"},
     {"content-length", "47"},
     {"connection", "keep-alive"}
   ],
   method: :get,
   opts: [],
   query: [],
   status: 200,
   url: "http://httpbin.org/digest-auth/auth/user/passwd"
 }}
iex(22)> TeslaTest.Fail.test
** (FunctionClauseError) no function clause matching in Tesla.Adapter.Hackney.handle/1    
    
    The following arguments were given to Tesla.Adapter.Hackney.handle/1:
    
        # 1
        {:ok, #Reference<0.2622084802.954990596.224118>}
    
    Attempted function clauses (showing 4 out of 4):
    
        defp handle({:error, _} = error)
        defp handle({:ok, status, headers})
        defp handle({:ok, status, headers, ref}) when is_reference(ref)
        defp handle({:ok, status, headers, body})
    
    (tesla) lib/tesla/adapter/hackney.ex:81: Tesla.Adapter.Hackney.handle/1
    (tesla) lib/tesla/adapter/hackney.ex:31: Tesla.Adapter.Hackney.call/2
    (tesla) lib/tesla/middleware/digest_auth.ex:57: Tesla.Middleware.DigestAuth.authorization_vars/2
    (tesla) lib/tesla/middleware/digest_auth.ex:47: Tesla.Middleware.DigestAuth.authorization_header/2
    (tesla) lib/tesla/middleware/digest_auth.ex:38: Tesla.Middleware.DigestAuth.call/3
~~~

**Comment by teamon** [comment]
@hodak Could you take a look?

**Comment by hodak** [comment]
I've never used hackney's `async` option and didn't need it for my DigestAuth use case. I guess it's a valid request, but, off the top of my head, I don't know how to fix it.

As mentioned in the doc https://hexdocs.pm/tesla/Tesla.Middleware.DigestAuth.html

> NOTE: Currently the implementation is incomplete and works only for MD5 algorithm and auth qop.

`DigestAuth` middleware is not a complete implementation and I finished implementation on what I needed then.

**Comment by adkron** [comment]
I'd like to help with this.

It looks like the real problem is in the hackney handler, but that would need to transfer the ref back to the caller, in this case, the auth, so that the auth system can handle getting the response from the reference.

I'm a little concerned about the choices that are made here since the response with the digest will end, but some streaming responses, like mjpg, will theoretically never end. I think there needs to be a callback implemented in the module utilizing async, but I'm not sure of how the API should handle that.

Thoughts?
