### ISSUE TITLE
httpc - Content-Type in request header is being ignored

### ISSUE THREAD

**Issue by chulkilee** [teamon/tesla#307]
See https://github.com/teamon/tesla/blob/v1.2.1/lib/tesla/adapter/httpc.ex#L48

- httpc adopter downcases response headers, but not request headers 
- httpc requires content-type in func calls - but httpc adopter checks only `content-type`

**Comment by teamon** [comment]
Why is that a problem? Tesla supports lowercase headers only as input.

**Comment by teamon** [comment]
@chulkilee 👋

**Comment by chulkilee** [comment]
> Why is that a problem? 

See https://github.com/chulkilee/ex_force/issues/32

- Use `Tesla.Middleware.Json`
- Pass `Content-Type` header in individual call (e.g. `text/csv`)

The final outgoing request header is not the one set in the func call (`text/csv`) but by `Tesla.Middleware.Json` middleware, since the middleware did not detect the given value and thus overwrite the value.

> Tesla supports lowercase headers only as input.

Hm is it documented? Anyway, it would be better to convert it in Tesla, instead of requiring users to downcase always I guess - some HTTP libraries does that as 1) per spec that is the semantic and 2) it simplifies internal processing (e.g. accessing request header later).

**Comment by teamon** [comment]
IIRC I decided to not force downcase request headers so you could use `Camel-Case` when dealing with some obscure http services that absolutely required case to match.

I'm going to close this one as not actionable, please do let me know if you think there is anything we can do here (expect for force-downcase headers)

**Comment by tobstarr** [comment]
> Why is that a problem? Tesla supports lowercase headers only as input.

@teamon just getting started with tesla I find this behavior a bit confusing, especially when dealing with the `Content-Type` header.

I do not have any issues with downcasing all headers (e.g. when providing `headers: [{"Foo", "bar"}]` I do see the header `foo: bar`) but if I want to provide a content-type via `headers: [{"Content-Type", "bar"}]` the header is not set (but instead a blank value is used) so I am forced to use `content-type`.

I personally woulder rather either also see `Content-Type` to be supported (and just downcased) or an error raised if the headers are not all downcased. Could this be considered a bug?
