### ISSUE TITLE
Set Accept-Encoding request header when using compression

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [teamon/tesla#312]
Currently when using `{Compression, [format: "gzip"]}` middleware (or "deflate") a corresponding request header is not set automatically.
When using the Tesla client the header needs to be set with every request.
If not, compression does not work (except for the bodies of posts).
```
Tesla.get client, "/some-path", headers: [{"Accept-Encoding", "gzip"}])
```

**Comment by i-n-g-m-a-r** [comment]
it seems when also using JSON middleware, the response body is not decompressed before it is decoded resulting in an error.
Maybe the ordering of the middleware has something to do with this.

**Comment by teamon** [comment]
@amatalai Could you take a look at this?

**Comment by RyanSiu1995** [comment]
1. For the first issue, I believe we can release an API for user to edit both incoming and outgoing format. I prefer to decouple two these parameters because `content-type` has an exact value. But `accept-encoding` can have multiple values.
2. I cannot reproduce the error. My test case is like this. The ordering does no effect to the result. Can you please provide us with your test case?
```elixir
  defmodule Client do
    use Tesla

    plug Tesla.Middleware.Compression
    plug Tesla.Middleware.JSON

    adapter fn env ->
      {status, headers, body} =
        case env.url do
          "/" ->
            {200, [{"content-type", "application/json"}], :zlib.gunzip(env.body)}
        end

      {:ok, %{env | status: status, headers: headers, body: body}}
    end
  end

  test "compress test" do
    assert {:ok, env} = Client.post("/", "{\"test\":\"test\"}")
    assert env.body == %{"test" => "test"}
  end
```

**Comment by amatalai** [comment]
> Maybe the ordering of the middleware has something to do with this.

Yes, the order of middlewares matters. Server response should be decompressed before it can be decoded. We can check this without doing an actual request with following code:
```elixir
# prepare "response"
iex()>server_response = %{a: "test", b: 1} |> Jason.encode! |> :zlib.gzip
<<31, 139, 8, 0, 0, 0, 0, 0, 0, 19, 171, 86, 74, 84, 178, 82, 42, 73, 45, 46,
  81, 210, 81, 74, 82, 178, 50, 172, 5, 0, 126, 238, 154, 211, 18, 0, 0, 0>>

# reverting process
iex()> server_response |> :zlib.gunzip |> Jason.decode!
%{"a" => "test", "b" => 1}

# try to decode json before gunzip
iex()>  server_response |> Jason.decode! |> :zlib.gunzip
** (Jason.DecodeError) unexpected byte at position 0: 0x1F
    (jason) lib/jason.ex:78: Jason.decode!/2
```

As far as I remember `Compression` middleware should be the last one

**Comment by amatalai** [comment]
Wrong order of middlewares also explains why a header wasn't added to the request. Let's look at the current implementation: https://github.com/teamon/tesla/blob/4f87d4b55b4ac4608f5392b3e4e4cbb775a73541/lib/tesla/middleware/compression.ex#L30-L45
If body wasn't JSON-encoded yet then there's big chance that it wasn't a binary and if it wasn't binary then `compressable?/1` returned false and nothing was changed in request env.
In retrospect, I think a better solution would be to raise error if `compressable?` check fails but now it would be breaking change 😞

**Comment by RyanSiu1995** [comment]
@amatalai From my test case, the order doesn't matter at all. No matter which middleware it comes first, the test case will still be passed.

**Comment by teamon** [comment]
@i-n-g-m-a-r Please provide a failing test case for your case.

**Comment by teamon** [comment]
@i-n-g-m-a-r Closing this one due to inactivity. Feel free to reopen.
