### ISSUE TITLE
Update dependency on mint

### ISSUE THREAD

**Issue by adriankumpf** [teamon/tesla#317]
I just wanted to try out the new mint adapter and noticed that the dependency on `:mint` is a bit outdated. The latest version is:

```elixir
{:mint, "~> 0.4"},
{:castore, "~> 0.1"},
```

**Comment by adriankumpf** [comment]
Thank you!

**Comment by teamon** [comment]
Good catch! I've republished the release to hex with updated & relaxed dependencies.
