### ISSUE TITLE
telemetry events has zero context when the request fails

### ISSUE THREAD

**Issue by lucasmazza** [teamon/tesla#327]
While debugging some timeouts on our app I noticed that our telemetry handler couldn't log properly which request failed. Looking on the source code, it seems that if `run/2` returns an `:error` tuple, no request info is sent to the handlers because the `env` will be only present when it returns `{:ok, env}`:

https://github.com/teamon/tesla/blob/3f82be43bff1d9bc9f1121e3170d23232266937e/lib/tesla/middleware/telemetry.ex#L27-L28

Should the `meta` argument have an `env` key with the pre-request env struct?

**Comment by teamon** [comment]
See https://github.com/teamon/tesla/pull/324 for ongoing improvement work
