### ISSUE TITLE
Better multipart support

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#34]
e.g. for hackney:

```
{:file, path, {"form-data", [{"name", "attachments[]"}, {"filename", filename}]}, []},
```

see multipart branch for more
- [ ] better syntax
- [ ] skip json middleware?
- [ ] multipart as middleware?

**Comment by veverkap** [comment]
@teamon is there an easy way in tesla to do this today?  Or do we need to rely on the lower level adapter?

**Comment by teamon** [comment]
@veverkap please see the recently released https://github.com/teamon/tesla#multipart-functionality (requires tesla 0.8.0+)

**Comment by veverkap** [comment]
Awesome!  Thanks
