### ISSUE TITLE
TLS 1.2?

### ISSUE THREAD

**Issue by cliffom** [teamon/tesla#35]
I have an API endpoint that requires TLS 1.2. Right now any request I make to that endpoint fails with:

```
** (Tesla.Error) adapter error: {:failed_connect, [{:to_address, {'test-api.tokenex.com', 443}}, {:inet, [:inet], {:tls_alert, 'handshake failure'}}]}
```

Elixir 1.3.4
Erlang/OTP 19

**Comment by teamon** [comment]
What adapter are you using? By default tesla uses httpc and I'm not sure it
supports ssl at all. You might want to try with hackney instead.

**Comment by cliffom** [comment]
I've tried with both hackney and ibrowse. Using httpc I was able to issue a request to https://www.google.com

**Comment by cliffom** [comment]
Actually I am not trying with Hackney and get the following:

```
** (UndefinedFunctionError) function Tesla.Adapter.Hackney.call/2 is undefined (module Tesla.Adapter.Hackney is not available)
     stacktrace:
       Tesla.Adapter.Hackney.call(%Tesla.Env{body: "{\"TokenScheme\":1,\"TokenExID\":\"XXX\",\"Data\":\"4242424242424242\",\"APIKey\":\"XXX\"}", headers: %{"content-type" => "application/json"}, method: :post, opts: [], query: [], status: nil, url: "https://test-api.tokenex.com/TokenServices.svc/REST/Tokenize"}, nil)
       lib/tesla/middleware/core.ex:5: Tesla.Middleware.Normalize.call/3
       lib/tesla/middleware/json.ex:21: Tesla.Middleware.JSON.call/3
       (tokenex) lib/tokenex.ex:15: TokenEx.tokenize/2
       test/tokenex_test.exs:9: (test)
```

Everything is setup correctly:
```
iex(1)> Code.ensure_loaded?(:hackney)
true
```

**Comment by teamon** [comment]
@cliffom I just pushed some basic SSL test cases - they pass on all adapters.

I can take a closer look at your specific endpoint, if you can't share it in this thread drop me an email at `i @ teamon.eu`

**Comment by teamon** [comment]
This seems to be more of a general issue with erlang & TLS 1.2 since all three adapters return

```
[error] SSL: :hello: ssl_alert.erl:97:Fatal error: handshake failure
```

I'll keep digging.

**Comment by cliffom** [comment]
Yea that is the exact issue I'm having. I agree, I think it is a TLS 1.2 issue and Erlang but don't know enough of the details to dig further. Let me know what you find, my project is basically halted because of this :(

**Comment by teamon** [comment]
https://github.com/benoitc/hackney/issues/344 seems to be related

**Comment by teamon** [comment]
Workaround for now:

```elixir
defmodule Client do
  use Tesla
  adapter :hackney, [ssl_options: [{:versions, [:'tlsv1.2']}]]
end
```

```
iex(1)> Client.get("https://www.bbc.co.uk").status
200
```

**Comment by cliffom** [comment]
This worked perfectly! Thank you for the assistance. So it appears the error is inherent to Erlangs SSL implementation?

**Comment by teamon** [comment]
Yes, it seems like erlang's ssl module is trying various versions in order that does not conform to spec (or something close to that).

Let's keep this issue open in case someone else encounter it until it is properly resolved.
