### ISSUE TITLE
Make Fuse return original error when circuit is closed

### ISSUE THREAD

**Issue by asniaire** [teamon/tesla#351]
## Problem
`Fuse` middleware is returning `{:error, :unavailable}` when circuit is open (expected) 
https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/fuse.ex#L58

But also when the call has failed, hidden the original error.
https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/fuse.ex#L73

I think it would be interesting to return the original error or maybe include a third element in the tuple including the original element.

For me, it's interesting to know when the circuit is open and the request never takes place, and know when the call has been performed with error as result.

## Timeout middleware integration
I ask for this after using `Timeout` and `Fuse` middlewares. For me, it makes sense to keep the order `Fuse` -> `Timeout`, so that if there is a timeout error, Fuse is aware of this when calculating its circuit status. But doing it, the original `{:error, :timeout}` is hidden by Fuse, returning `{:error, :unavailable}`. And I'd like to know that `timeout` was the original problem.

**Comment by asniaire** [comment]
Another point I've realised is that, if `Tesla` gets a `5xx` error it returns `{:ok, %Tesla.Env{status: 5xx}` and it seems it's taken by `Fuse` as a successful response. So, it's not considered to melt the fuse. That is, to open the circuit.

Is it right? If so, is it the expected behaviour for a `circuit breaker`?

And maybe even http status `429` (`Too many requests`) should be considered by `Fuse`?

Thanks!

**Comment by teamon** [comment]
It's impossible to have one-size-fits-all answer for "to melt or not to melt".
For the same reasons Retry middleware exposes (`should_retry` function](https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/retry.ex#L32), Fuse middleware could use the same.

**Comment by asniaire** [comment]
Yes! It was just was I was about to propose. Having an optional configuration to let the client decide which http status you want to consider to melt.

If you agree, I'll submit an MR containing this proposal.

Not sure if do exactly the same as `Retry` of just passing a list of http status codes 🤔

**Comment by teamon** [comment]
Let's do the same as in Retry for consistency (also list of http status codes might not be enough)

**Comment by asniaire** [comment]
Sure! It was just to make the clients simpler. But let's do the same way as `Retry` for consistency, yes :)

**Comment by asniaire** [comment]
BTW, one thing is when the request should be melt according to the response (solved doing the same as `Retry`). And different one is what should we return if it happens. That's the original question of this issue. 

For me, it makes sense to return the original error even it has been selected to melt. And only return specific `circuit breaker` error when it's open. 

Because having another function as param to decide when to return original response is too much.

What do you think?

**Comment by asniaire** [comment]
To clarify, this existing test would be:

```elixir
test "unavailable endpoint" do
    assert {:error, :econnrefused} = Client.get("/unavailable")
    assert_receive :request_made
    assert {:error, :econnrefused} = Client.get("/unavailable")
    assert_receive :request_made
    assert {:error, :econnrefused} = Client.get("/unavailable")
    assert_receive :request_made

    assert {:error, :unavailable} = Client.get("/unavailable")
    refute_receive :request_made
    assert {:error, :unavailable} = Client.get("/unavailable")
    refute_receive :request_made
  end
```

**Comment by asniaire** [comment]
The only drawback I see here is that it wouldn't be backward compatible, would it? 

Unless we add a parameter to decide if we want to keep the original response when the circuit is close, keeping the current behaviour as default one.

IMHO, it should be the right behaviour. I want my response unless you don't perform the request because the circuit is open.

**Comment by teamon** [comment]
I don't see this as a huge backwards compatibility issue - let's go with this change.
