### ISSUE TITLE
Allow middleware to set TLS/SSL options

### ISSUE THREAD

**Issue by tanguilp** [teamon/tesla#352]
I may have misread the doc, but I didn't find a way to modify SSL/TLS options from a middleware.

My use case is to implement an authentication middleware for TLS client authentication. In this scheme, a client sets its private key in the TLS options. Not that the setting is not global: each outbound request can have a different client certificate set.

**Comment by teamon** [comment]
The `%Tesla.Env{}` does not hold SSL options - they can be only passed to the adapter.

However, you have two options:

#### 1. Wrap adapter

```elixir
defmodule MyAdapter do
  def call(env, opts) do
    opts = insert_custom_ssl_opts(env, opts)
    Tesla.Adapter.Mint.call(env, opts) # or any other adapter
  end
end

defmodule MyClient do
  use Tesla
  adapter MyAdapter
end 
```

#### 2. Use [runtime adapter](https://github.com/teamon/tesla#runtime-middleware)

```elixir
defmodule MyClient do
  def new(user) do
    adapter = {Tesla.Adapter.Mint, ssl_opts(user)}
    middleware = [ ... ]
    Tesla.client(middleware, adapter)
  end

  def do_somthing(client) do
    Tesla.get(client, "/something")
  end
end

client = MyClient.new(user)
MyClient.do_something(client)
```

**Comment by tanguilp** [comment]
Thanks for the swift answer.

However, the 2 options proposed kind defeat the purpose of Tesla in the first place, which is to allow to seamlessly change the adapter. When writing this issue, I meant it as a request for a change in Tesla to make it possible without being dependant on a specific adapter :) Of course, this could require too many changes for a rare use-case. What do you thing?

**Comment by chulkilee** [comment]
Middleware is not aware of adapter - we may make each adapter accept same format of SSL configuration instead.

> However, the 2 options proposed kind defeat the purpose of Tesla in the first place, which is to allow to seamlessly change the adapter. 

Please note that adapters are actually not providing the same consistent interface for "adapter options". That's not the main goal of adapter for now - it's to have minimal abstraction layer for Tesla requset/response life cycles.

Instead, we may make adapter to accept the same config structure for SSL - but that may worth to consider - but not sure we can achieve that for other options (e.g. some may have different semantic or granularity). That's why adapter option is being passed to the actual backed as-is mostly.

And in reality, you only need to change one single function to switch adapter! I don't think "swapping backend" means "without any code change" necessarily...

BTW if you need to do per-request SSL verification or authentication.. then it would be better to use dynamic client. That's not expensive at all - and you have more control..

**Comment by teamon** [comment]
While tesla do indeed allow to swap adapters, in reality this is very rarely a case (just like with ORMs).

I agree with @chulkilee - using dynamic client is the best way to go.

You _could_ (ab)use `env.opts[:adapter]`, but these options are passed straight to the adapter - the is no compatibility layer for adapter options (and each has different ones).

**Comment by tanguilp** [comment]
It seems to me that's the question indeed: is it worth adding this special case for SSL options. These SSL options are standard among adapters (or so I think) and could be used for SSL/TLS client authentication, and maybe other things (CA selection...).

My initial wish was to write a middleware for SSL/TLS client authentication just like the other authentication middlewares (BasicAuth and DigestAuth). This would be the ideal clean solution should the Tesla API have this SSL/TLS option setting interface.

**Comment by teamon** [comment]
Technically it is possible, but practically that would mean quite a lot of work and an even harder coupling, not to mention keeping an eye on multiple projects to check for updates - at this point I do not have the bandwidth to commit to something like that.

Can you share a bit more on why using any of the proposed solutions is not good enough for your use case?

**Comment by tanguilp** [comment]
My use-case is to write such a TLS/SSL client authentication middleware in a separate library, to be used by other projects without additional modification needed in their code.

Both solutions would work but require more than just writing `my_app |> Middlewares.get() |> Tesla.client() |> Tesla.post(...)`.

I think it would make sense to add a way to access SSL/TLS conf as an exception (for this type of use-case), and I also understand that it requires additional work. Although I think all adapters use the same SSL/TLS Erlang library options (haven't checked Mint though).

Another use-case I've just though of is Token Binding (https://en.wikipedia.org/wiki/Token_Binding). Not supported yet by Erlang's SSL/TLS stack but yet another example of applicative information conveyed in the TLS tunnel.

Just in case, would you consider a PR?

**Comment by chulkilee** [comment]
Technically that's possible - as SSL option is pretty "similar" across backends (e.g. using erlang `ssl` module`

However, HTTP libraries have different default behaviours - httpc does not verify ssl by default, hackney uses ssl_verify_fun  with certifi by default, mint uses castore optionally. Also hackney uses connection pool which shares TCP connection, thus SSL option is per connection pool, not per request (see https://github.com/benoitc/hackney/issues/570 )

I see the value of adding abstraction layer for SSL configuration in Tesla.. but I'm not sure that's worth do it as we may add more confusion or misleading. I think retry and timeout middleware have the same issue - working most cases, but it's not the 100% correct abstraction, so I think it would be better to have them as 3rd-party middleware, not the core tesla middleware.

**Comment by tanguilp** [comment]
> However, HTTP libraries have different default behaviours - httpc does not verify ssl by default, hackney uses ssl_verify_fun with certifi by default, mint uses castore optionally. Also hackney uses connection pool which shares TCP connection, thus SSL option is per connection pool, not per request (see benoitc/hackney#570 )

The problem with reuse of opened SSL connections when pooling could (and should) indeed be solved by introspecting SSL options. In my case, TLS authentication is for OAuth2 clients, which means applications and their private SSL authentication key seldom change, which would be less of a problem.

Another possible problem (haven't checked thoroughly though) would be that setting SSL options for client certificate would cancel other default options set by the adapter (verify_fun, etc.) unless these would be merged. It would then result in security issues, should the library's users not pay attention to that. And I think such merging of user-provided SSL options with default SSL options could only be implemented by the underlying library.

> I see the value of adding abstraction layer for SSL configuration in Tesla.. but I'm not sure that's worth do it as we may add more confusion or misleading.
Agree with both assertions. The core problem might be a design problem: I'm not sure using SSL level mechanisms for application level things was a good idea after all. Same problem with token binding protocol.

**Comment by teamon** [comment]
I don't think we can do much here right now - I'm going to close this issue.
If you have other comments or ideas please share them here.

**Comment by tanguilp** [comment]
I might propose a PR in the future. Thanks for the insights!
