### ISSUE TITLE
Redirect middleware does not consider changing host field

### ISSUE THREAD

**Issue by vfsoraki** [teamon/tesla#360]
When using FollowRedirect middleware, if `location` header has a different host, e.g. redirecting to `www.`, it does not change request header `host` to match it.

I have changed the middleware for myself to include this, and I can make a PR for it.

First I wanted to make sure this it not intended, or because of some other issues. I already searched issues for `redirect` and there is no relevant issue.

**Comment by teamon** [comment]
tesla does not manipulate `Host` header. Can you share an example of wrong behaviour?

**Comment by vfsoraki** [comment]
I see. I am passing customer headers, and my headers contain  `host` header for the request.

I see that a simple `Tesla.get("https://google.com")` does not have any headers in `Testa.Env` struct. So adapter is responsible to send correct `host` header.

I don't know what should be the expected behavior. My scenario look like this:

- I set initial headers, containing correct `host` header
- Response is a redirect to another domain (or a subdomain)
- We need to change `host` header for the next request

So question is, the responsibility to change `host` field for subsequent requests is to be given to:

- Current `FollowRedirects` middleware
- Adapter
- User (programmer)

I can share an example, but I think the issue (or question) is clear now. Let me know if you need a more concrete example.

**Comment by vfsoraki** [comment]
As a matter of fact, here is an example:

```
iex(1)> middlewares = [Tesla.Middleware.Logger, Tesla.Middleware.FollowRedirects]
[Tesla.Middleware.Logger, Tesla.Middleware.FollowRedirects]
iex(2)> client = Tesla.client(middlewares)                                       
%Tesla.Client{
  adapter: nil,
  fun: nil,
  post: [],
  pre: [
    {Tesla.Middleware.Logger, :call, [[]]},
    {Tesla.Middleware.FollowRedirects, :call, [[]]}
  ]
}
iex(3)> Tesla.get(client, "https://google.com")                                  

01:48:17.466 [info]  GET https://google.com -> 200 (1365.377 ms)
 
01:48:17.467 [debug] 
>>> REQUEST >>>
(no query)
(no headers)
(no body)

<<< RESPONSE <<<
cache-control: private, max-age=0
date: Tue, 03 Mar 2020 22:18:18 GMT
accept-ranges: none
server: gws
vary: Accept-Encoding
content-length: 46958
content-type: text/html; charset=ISO-8859-1
expires: -1
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
x-xss-protection: 0
x-frame-options: SAMEORIGIN
set-cookie: 1P_JAR=2020-03-03-22; expires=Thu, 02-Apr-2020 22:18:18 GMT; path=/; domain=.google.com; Secure
set-cookie: NID=199=sIQFKE0DJ7LRyi3InVosYAWLrUS5rWv9dJCENqN9HvFm1jb13NNeMCnyhMgyH6RVPVciWQpTmJAsGXo7qkpK-oynwhoL0jkFUXGL0lIsA_9PiPYd2LtVmK6HCGIZBp0W1Iz4czzINxt8KIDb081c_Ib-PvnABrcujFjmnD-vPPQ; expires=Wed, 02-Sep-2020 22:18:18 GMT; path=/; domain=.google.com; HttpOnly
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000

<some blah blah html css js>

{:ok,
 %Tesla.Env{
   __client__: %Tesla.Client{
     adapter: nil,
     fun: nil,
     post: [],
     pre: [
       {Tesla.Middleware.Logger, :call, [[]]},
       {Tesla.Middleware.FollowRedirects, :call, [[]]}
     ]
   },
   __module__: Tesla,
   body: "again some blah blah",
   headers: [
     {"cache-control", "private, max-age=0"},
     {"date", "Tue, 03 Mar 2020 22:18:18 GMT"},
     {"accept-ranges", "none"},
     {"server", "gws"},
     {"vary", "Accept-Encoding"},
     {"content-length", "46958"},
     {"content-type", "text/html; charset=ISO-8859-1"},
     {"expires", "-1"},
     {"p3p", "CP=\"This is not a P3P policy! See g.co/p3phelp for more info.\""},
     {"x-xss-protection", "0"},
     {"x-frame-options", "SAMEORIGIN"},
     {"set-cookie",
      "1P_JAR=2020-03-03-22; expires=Thu, 02-Apr-2020 22:18:18 GMT; path=/; domain=.google.com; Secure"},
     {"set-cookie",
      "NID=199=sIQFKE0DJ7LRyi3InVosYAWLrUS5rWv9dJCENqN9HvFm1jb13NNeMCnyhMgyH6RVPVciWQpTmJAsGXo7qkpK-oynwhoL0jkFUXGL0lIsA_9PiPYd2LtVmK6HCGIZBp0W1Iz4czzINxt8KIDb081c_Ib-PvnABrcujFjmnD-vPPQ; expires=Wed, 02-Sep-2020 22:18:18 GMT; path=/; domain=.google.com; HttpOnly"},
     {"alt-svc",
      "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000"}
   ],
   method: :get,
   opts: [],
   query: [],
   status: 200,
   url: "https://www.google.com/"
 }}
iex(4)> Tesla.get(client, "https://google.com", headers: [{"host", "google.com"}])

01:58:35.155 [error] GET https://google.com -> error: {Tesla.Middleware.FollowRedirects, :too_many_redirects} (1716.182 ms)
 
01:58:35.155 [debug] 
>>> REQUEST >>>
(no query)
host: google.com

(no body)

<<< RESPONSE ERROR <<<
{Tesla.Middleware.FollowRedirects, :too_many_redirects}
{:error, {Tesla.Middleware.FollowRedirects, :too_many_redirects}}

```

The error is caused by sending `google.com` as `host` header, whereas server requires `www.google.com`. When setting `host` header explicitly, `FollowRedirects` may not work as expected.

**Comment by teamon** [comment]
`httpc` somehow handles it correctly: 

```
iex(8)> :httpc.request(:get, {'https://google.com', [{'host', 'google.com'}]}, [autoredirect: false], [])
{:ok,
 {{'HTTP/1.1', 301, 'Moved Permanently'},
  [
    {'cache-control', 'public, max-age=2592000'},
    {'date', 'Wed, 04 Mar 2020 08:51:33 GMT'},
    {'location', 'https://www.google.com/'},
    {'server', 'gws'},
    {'content-length', '220'},
    {'content-type', 'text/html; charset=UTF-8'},
    {'expires', 'Fri, 03 Apr 2020 08:51:33 GMT'},
    {'x-xss-protection', '0'},
    {'x-frame-options', 'SAMEORIGIN'},
    {'alt-svc',
     '...'}
  ],
  '...'}}

iex(9)> :httpc.request(:get, {'https://google.com', [{'host', 'google.com'}]}, [autoredirect: true], [])
{:ok,
 {{'HTTP/1.1', 200, 'OK'},
  [
    {'cache-control', 'private, max-age=0'},
    {'date', 'Wed, 04 Mar 2020 08:51:37 GMT'},
    {'accept-ranges', 'none'},
    {'server', 'gws'},
    {'vary', 'Accept-Encoding'},
    {'content-length', '47482'},
    {'content-type', 'text/html; charset=ISO-8859-1'},
    {'expires', '-1'},
    {'p3p', 'CP="This is not a P3P policy! See g.co/p3phelp for more info."'},
    {'x-xss-protection', '0'},
    {'x-frame-options', 'SAMEORIGIN'},
    {'set-cookie',
     '...'},
    {'set-cookie',
     '...'},
    {'alt-svc',
     '...'}
  ],
  '...'}}
```

(tesla sets `autoredirect: false` to be compatible with other adapters).

The question really is: Which headers should be passed to following requests and which should be dropped. This is somehow related with https://github.com/teamon/tesla/issues/362

**Comment by chulkilee** [comment]
> I am passing customer headers, and my headers contain host header for the request.

May I ask why?

If you need to use different values between URL and `host` header (e.g. ip address in URL and custom `host` header for SNI...) then you may need to specify custom behavior on redirect (e.g. once redirected, Tesla doesn't know which `host` value is actually correct one).

**Comment by vfsoraki** [comment]
> > I am passing customer headers, and my headers contain host header for the request.
> 
> May I ask why?
> 
> If you need to use different values between URL and `host` header (e.g. ip address in URL and custom `host` header for SNI...) then you may need to specify custom behavior on redirect (e.g. once redirected, Tesla doesn't know which `host` value is actually correct one).

My case is a reverse proxy, with some custom response body manipulation in it. All headers from actual client is passed to endpoint, expect `host` which should be modified.

I haven't tested removing `host` header to see what happens. I will try it and report it.

**Comment by chulkilee** [comment]
Do you mean you need to set `host` to the actual backend host name while HTTP requests goes to the reverse proxy? (e.g. `http://reverseproxy.local` with `host: actual-backend.local`?)

One option (I prefer) is to use DNS(e.g. CNAME on backend.local to reverse.proxy).

However, if you cannot do that for some reasons - then I think it's safer to use custom redirect logic - instead of trusting `location` field from the actual backend - since the value may not be useful on client side (e.g. what if it returns `another-backend.local` and you also have to send it to `reverse-proxy.local` with custom `host` header?)

**Comment by vfsoraki** [comment]
> Do you mean you need to set `host` to the actual backend host name while HTTP requests goes to the reverse proxy? (e.g. `http://reverseproxy.local` with `host: actual-backend.local`?)
> 
> One option (I prefer) is to use DNS(e.g. CNAME on backend.local to reverse.proxy).
> 
> However, if you cannot do that for some reasons - then I think it's safer to use custom redirect logic - instead of trusting `location` field from the actual backend - since the value may not be useful on client side (e.g. what if it returns `another-backend.local` and you also have to send it to `reverse-proxy.local` with custom `host` header?)

I didn't quite get what you said.

I don't pass redirection to client, I resolve it in proxy, then pass the final content to client.

I can't use CNAME, backends are not ours and we do not control them, nor we control the clients. Backends are also multiple different domains, and are dynamic (meaning could change anytime, client instructs proxy with a special parameter to choose a specific backend).

I did write my own redirection middleware, based on the official one. I just opened issue to inform and discuss the (probably) problem here.

**Comment by chulkilee** [comment]
> I don't pass redirection to client, I resolve it in proxy, then pass the final content to client.

What is "I" here? Are you implementing reverse proxy like this?

```
client -[call yourapp.com]-> YourApp -[call backend1.com]-> backend1
```

And you need to handle redirect response header from backend1? (e.g. going to backend2)

----

BTW...

I agree that redirect middleware should drop `host` header, if the resolved location has different hostname, since the new request is going to different host, and the `host` header is *specific* to the request to the original host in the url.

**Comment by vfsoraki** [comment]
> > I don't pass redirection to client, I resolve it in proxy, then pass the final content to client.
> 
> What is "I" here? Are you implementing reverse proxy like this?
> 
> ```
> client -[call yourapp.com]-> YourApp -[call backend1.com]-> backend1
> ```
> 
> And you need to handle redirect response header from backend1? (e.g. going to backend2)
> 
> BTW...
> 
> I agree that redirect middleware should drop `host` header, if the resolved location has different hostname, since the new request is going to different host, and the `host` header is _specific_ to the request to the original host in the url.

Yes, that's how it works, considering dynamic backend chosen by a certain parameter from client while calling yourapp.com.

And I mostly agree with you. `host` header should be handled automatically. But then we can also think that maybe there is a use case to pin `host` header and prevent the middleware from changing it. Maybe someone wants (and maybe currently is using without knowing) this behavior.

**Comment by teamon** [comment]
I agree, `FollowRedirects` should drop host header in case the location has a different hostname than the original url.

**Comment by teamon** [comment]
Since #372 has been merged, I think we can close this one.
