### ISSUE TITLE
Leaking Secrets on Redirect!

### ISSUE THREAD

**Issue by lizziepaquette** [teamon/tesla#362]
Same issue as myfreeweb/httpotion#135

Pull request here: https://github.com/teamon/tesla/pull/361

**Comment by lizziepaquette** [comment]
@teamon I see you triaged, any thoughts on the fix?

**Comment by chulkilee** [comment]
Where can we find the guideline for this? I don't think HTTP spec say anything about resending *any header*, and I guess there are "common" practice (e.g. by browser or popular http library).

Some notes:

- Why is only `authorization` header special? For example, there might be other headers with credentials
- What if when resending all header (including headers for credentials) is needed?
  - e.g. if the new location is relative path, or absolute but still in the same host (e.g. HATEOAS style)

**Comment by teamon** [comment]
@lizziepaquette I am at the same point as @chulkilee here - it is trivial to implement it, but it might be very wrong. 

So far I think a reasonable option would be to:
- Add `:should_pass_auth_headers` option which defaults to `prev.host == next.host`
- Add `:pass_auth_headers` option which defaults to `["authorization"]`

I think with the above defaults we could treat this as a bug fix instead of a breaking change.

**Comment by lizziepaquette** [comment]
While the HTTP spec doesn't have any explicit guidelines here I think it would be best to follow what curl does in this case: https://github.com/curl/curl/blob/6beb0eee/lib/http.c#L710

```
  /* To prevent the user+password to get sent to other than the original
     host due to a location-follow, we do some weirdo checks here */
  if(!data->state.this_is_a_follow ||
     conn->bits.netrc ||
     !data->state.first_host ||
     data->set.http_disable_hostname_check_before_authentication ||
     Curl_raw_equal(data->state.first_host, conn->host.name)) {
    result = output_auth_headers(conn, authhost, request, path, FALSE);
  }
  else
    authhost->done = TRUE;

  return result;
}
```
curl has a flag --location-trusted http://www.mit.edu/afs.new/sipb/user/ssen/src/curl-7.11.1/docs/curl.html#--location-trusted that allows the auth headers to be sent on redirects, but without that flag specified the auth headers are not sent if redirect's host is different from the first host. 

Right now auth headers are being sent through redirects without anyone expecting them to (as it is usually opt in). My pr stops the bleeding but does aggressively scrub the auth headers, not checking the host.

**Comment by teamon** [comment]
Let's continue in https://github.com/teamon/tesla/pull/371

**Comment by teamon** [comment]
Solved by https://github.com/teamon/tesla/pull/371
