### ISSUE TITLE
No easy way to make a POST request?

### ISSUE THREAD

**Issue by sayplastic** [teamon/tesla#38]
The only example from the documentation works:

`Tesla.post("http://httpbin.org/post", "data", headers: %{"Content-Type" => "application/json"})`

None of the following work:

`Tesla.post("http://httpbin.org/post", %{key: "value"}`
`Tesla.post("http://httpbin.org/get", query: [a: 1, b: "foo"])`

Isn't it kind of counterintuitive?
Matter of fact, I've looked through the code but couldn't find _any_ other way to perform a post request with parameters.

**Comment by teamon** [comment]
I'm not sure I understand your question, but I'll try to answer it anyway :)

You can send a POST request using `Tesla.post` function (or `YourApi.post`).
The arguments are: `def post(url, payload, options \\ [])`. 
By default the payload is sent as-is. Let me show this using few examples:


Sending raw data:
```elixir
iex(1)> Tesla.post("http://httpbin.org/post", "my-post-data").body |> IO.puts
{
  "args": {},
  "data": "my-post-data",
  "files": {},
  "form": {},
  "headers": {
    "Content-Length": "12",
    "Content-Type": "",
    "Host": "httpbin.org"
  },
  "json": null,
  "origin": "89.65.176.175",
  "url": "http://httpbin.org/post"
}
```

Sending form data:

```elixir
iex(2)> Tesla.post("http://httpbin.org/post", "a=1&b=2", headers: %{"content-type": "application/x-www-form-urlencoded"}).body |> IO.puts
{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "a": "1",
    "b": "2"
  },
  "headers": {
    "Content-Length": "7",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org"
  },
  "json": null,
  "origin": "89.65.176.175",
  "url": "http://httpbin.org/post"
}
```

Sending JSON:

```elixir
iex(3)> Tesla.post("http://httpbin.org/post", ~s'{"hello": 123}', headers: %{"content-type": "application/json"}).body |> IO.puts
{
  "args": {},
  "data": "{\"hello\": 123}",
  "files": {},
  "form": {},
  "headers": {
    "Content-Length": "14",
    "Content-Type": "application/json",
    "Host": "httpbin.org"
  },
  "json": {
    "hello": 123
  },
  "origin": "89.65.176.175",
  "url": "http://httpbin.org/post"
}
```

Tesla does not assume what kind of content you want to send.

Obviously, when building an API client we would like to avoid repetition, like e.g. json encoding the payload. That's what middlewares are for.

```elixir
defmodule Httpbin do
  use Tesla

  plug Tesla.Middleware.BaseUrl, "http://httpbin.org/"
  plug Tesla.Middleware.JSON
end
```

and then

```elixir
iex(4)> Httpbin.post("/post", %{"a" => 1}).body
%{"args" => %{}, "data" => "{\"a\":1}", "files" => %{}, "form" => %{},
  "headers" => %{"Content-Length" => "7", "Content-Type" => "application/json",
    "Host" => "httpbin.org"}, "json" => %{"a" => 1},
  "origin" => "89.65.176.175", "url" => "http://httpbin.org/post"}
```

The `Tesla.Middleware.JSON` middleware takes care of both encoding the payload as json, adding correct 'Content-Type' header, as well as decoding the response from JSON.

Please let me know if that answers your question.

**Comment by sayplastic** [comment]
Thank you for your response. To be precise, I mean sending _application/x-www-form-urlencoded params_ in POST requests. HTTPoison does it like this:

`HTTPoison.post(url, {:form, [key: "value"]})`

I realize now that I can encode it manually, but this just seems like a mundane task (that is already solved in a lot of clients/languages that I'm coming from).

**Comment by teamon** [comment]
Currently there is no `FormUrlencoded` middleware (simply because I never needed it) but it should be straightforward to add (see json.ex).

Tesla was built with custom API clients in mind. There are not many use cases for direct usage of `Tesla.get/post` functions - you would rather build a custom module and choose whatever middlewares you need.

**Comment by sayplastic** [comment]
Fair enough. I'll see if I can make this into a pull request. Thanks!
