### ISSUE TITLE
Finch adapter

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#381]
A tiny adapter for https://github.com/keathley/finch - a HTTP client with built-in pooling. 
Instead of building own mint+pooling adapter we could nicely integrate with Finch.

Something like this:

```elixir
defmodule Tesla.Adapter.Finch do
  @behaviour Tesla.Adapter

  def call(env, opts) do
    opts = Tesla.Adapter.opts(env, opts)    
    case Finch.request(name, env.method, env.url, env.headers, env.body, opts) do
      {:ok, ...} ->  # convert finch's response to %Tesla.Env{}
      {:error, ...} -> # ensure proper error handling
    end
  end
end
```

**Comment by chulkilee** [comment]
Note

> Pools will be started for each configured `{scheme, host, port}` when Finch is started. For any unconfigured `{scheme, host, port}`, the pool will be started the first time it is requested. Note pools are not automatically terminated if they are unused, so Finch is best suited when you are requesting a known list of static hosts.

So I believe we need a way to trigger pruning unused pools (or a way to do it) from the library.

**Comment by Monyk015** [comment]
Hey. I'm trying my hand at implementing this adapter and I'm not sure what to do with multipart and streaming. Finch's API doesn't seem to support it even though Mint does.

**Comment by keathley** [comment]
@Monyk015 There is an open issue on finch to support a streaming API: https://github.com/keathley/finch/issues/58

**Comment by keathley** [comment]
@Monyk015 streaming support has been added to finch: https://github.com/keathley/finch/pull/59

**Comment by jrusso1020** [comment]
Hi @teamon my team needed to use a proxy with the Finch adapter, I wanted to pass in the `:proxy` and `:proxy_headers` to the pool based on this issue's examples https://github.com/keathley/finch/issues/85 like so
```
middleware = [...]

pool_opts = %{
  :default => [
    size: 5, 
    conn_opts: [
    proxy_headers: [{"proxy-authorization", "Basic " <> Base.encode64("#{proxy_user}:#{proxy_password}"}],
    proxy: {
      :http, 
      proxy_host, 
      proxy_port, 
      []
      }
    ]
  ]
}

adapter = {Tesla.Adapter.Finch, name: NamespaceFinch, pool: pool_opts }

Tesla.client(middleware, adapter)
```

But looking at the current Finch adapter it looks like we only expect three options

What do you think about doing something similar to this PR https://github.com/teamon/tesla/pull/417/files where we just pass the opts from the adapter to the Finch request directly? This way we can support all Finch options
