### ISSUE TITLE
Feature Request: Allow client meta data that can be passed to Telemetry

### ISSUE THREAD

**Issue by aselder** [teamon/tesla#386]
When using Tesla following the Runtime Middleware style, the telemetry events emitted do not contain any information about which Tesla client emitted the event. The `__module__` attributes of the env is simply `Tesla`. 

Perhaps we could add a metadata field to Tesla.Client that can be populated with arbitrary values when `Tesla.client()` is called?

**Comment by aselder** [comment]
I'm happy to put in the work and I think it would be pretty simple.

 I'm thinking of changing the second argument to `Tesla.client/2` to a keyword list that could take `adapter` and `metadata` values. I'd add a backwards compatibility layer to `Tesla.client/2` so that it would not break existing code (if 2nd arg is keyword list, find the adapater under the adapter key, otherwise treat the 2nd arg as an adapter).

This additional metadata would be stored in the client and passed around as part of the env. This would make it available in the Telemetry events.

I'd love to hear people's thoughts on this approach.

**Comment by aselder** [comment]
Initial rough implementation: https://github.com/teamon/tesla/pull/387. Would love to get thoughts and feedback.

**Comment by teamon** [comment]
Hi, would https://github.com/teamon/tesla/pull/390 solve the issue?

**Comment by aselder** [comment]
@teamon That would fit the bill perfectly! Thanks. I'll close #387
