### ISSUE TITLE
How to handle failures?

### ISSUE THREAD

**Issue by kaikuchn** [teamon/tesla#391]
Hi, I'm picking up elixir again and one project I'm working on uses this library. I apologise if this isn't the right place to ask, but I couldn't find any community chat or similar linked in the readme.

Anyway, I have trouble handling errors since most middlewares only handle the `{:ok, _}` tuple but in some cases an `{:error, _}` tuple is being returned. I don't want to rescue the `MatchError`, so instead I inserted a middleware near the bottom, just above the fuse middleware, that handles error tuples and raises a `Tesla.Error`. That I can then rescue in my application code and perform my custom handling since I don't want to crash.

Is this the way to do it?

For the sake of completeness, here's the relevant code:
```elixir
defmodule Foo.ApiClient do
  use Tesla, only: [:get]

  adapter(Tesla.Adapter.Hackney, recv_timeout: 10_000)

  @config Application.get_env(:bar, Foo)

  plug Tesla.Middleware.BaseUrl, @config[:base_uri]
  plug Tesla.Middleware.DecodeJson, decode_content_types: ["application/vnd.api+json"]
  plug Tesla.Middleware.Headers, [{"Accept", "application/json, application/vnd.api+json"}]
  plug Tesla.Middleware.Cache, ttl: :timer.hours(24)
  plug Tesla.Middleware.ThrowError
  plug Tesla.Middleware.Fuse, opts: {{:standard, 3, 10_000}, {:reset, 60_000}}

  def forward("/foo" <> path), do: forward(path)
  def forward(path) do
    try do
      get(path)
    rescue
      e in Tesla.Error -> {:error, e.reason}
    end
  end
end
```

And the middleware i wrote:

```elixir
defmodule Tesla.Middleware.ThrowError do
  @moduledoc """
  Exit the middleware chain when receiving an :error tuple by raising a Tesla.Error
  """
  def call(env, next, _opts) do
    case Tesla.run(env, next) do
      {:error, e} -> raise %Tesla.Error{reason: e}
      x -> x
    end
  end
end
```

If I wouldn't insert the `ThrowError` middleware then the `Cache` middleware would crash on `{:error, :unavailable}` if the fuse melts for instance.

**Comment by teamon** [comment]
Hi,

All middleware must handle both `{:ok, env}` and `{:error, ...}` results returned from `Tesla.run()`. It seems the problem is with `Tesla.Middleware.Cache` which is not part of tesla core library, but is a separate library - https://github.com/emerleite/tesla_cache. I recomment opening an issue there.
