### ISSUE TITLE
:idna module is called in Gun adapter, but not included in deps

### ISSUE THREAD

**Issue by mpinkston** [teamon/tesla#392]
This is a pretty minor inconvenience, but could cause some confusion for folks trying to make requests to `'localhost'` if the `:idna` module isn't already available in deps.

**Comment by teamon** [comment]
@alex-strizhakov Would you mind taking a look?

**Comment by alex-strizhakov** [comment]
is it enough that `idna` dep is mentioned in gun docs?

**Comment by teamon** [comment]
I think we could mention it in adapter docs like [we do with mint](https://hexdocs.pm/tesla/Tesla.Adapter.Mint.html#content)

**Comment by alex-strizhakov** [comment]
@teamon 👌 i've updated docs

**Comment by mpinkston** [comment]
I'd certainly call this sufficient, thanks!
