### ISSUE TITLE
How to configure proxy dynamically ?

### ISSUE THREAD

**Issue by collegeimprovements** [teamon/tesla#401]
Hi @teamon,

Thanks a lot for Tesla. It's being super useful to me.
The following is not a bug or feature request. 
But rather it's a call for guidance. 

I've this code: 
```
defmodule Tesla.MyApi do
  use Tesla

  @me __MODULE__

  @proxy {:http, "proxy-host", 8080, []}
  adapter(Tesla.Adapter.Mint, proxy: @proxy)

  plug(Tesla.Middleware.BaseUrl, "https://base-url")

end
```

This works great when we have proxy. 
However sometimes we don't have proxy and in those cases we just want `adapter(Tesla.Adapter.Mint)` line without `proxy: @proxy` and `@proxy` attribute. 

How to achieve that ?
We have `PROXY_REQUIRED: true` or `PROXY_REQUIRED: false`  env variable to decide that.

Thanks

**Comment by teamon** [comment]
Take a look at [dynamic client configuration](https://github.com/teamon/tesla#runtime-middleware)

**Comment by collegeimprovements** [comment]
Thanks a lot teamon.
