### ISSUE TITLE
Logger Middleware does not have query variable

### ISSUE THREAD

**Issue by alexander7161** [teamon/tesla#413]
When using the logger middleware and using https://hexdocs.pm/tesla/Tesla.Middleware.Logger.html#module-custom-log-format you should be able to print the query params.

Query should be added here:

https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/logger.ex#L30

**Comment by Ch4s3** [comment]
@teamon and/or @teamon I took a quick stab at this with this PR https://github.com/teamon/tesla/pull/422. If you have any feedback, that would be great!

**Comment by alexander7161** [comment]
Thanks @Ch4s3 !
