### ISSUE TITLE
Middleware.Retry does not work with zero delay

### ISSUE THREAD

**Issue by Fedjmike** [teamon/tesla#415]
If I pass `delay` and `max_delay`  options to `Tesla.Middleware.Retry` to specify no delay, an error is thrown from `:rand.uniform`. https://github.com/teamon/tesla/blob/v1.3.3/lib/tesla/middleware/retry.ex#L96

I think this should be checked against, like so:

```
defp backoff(cap, base, attempt) do
  factor = :math.pow(2, attempt)
  max_sleep = trunc(min(cap, base * factor))

  unless max_sleep == 0 do
    delay = :rand.uniform(max_sleep)
    :timer.sleep(delay)
  end
end
```

**Comment by britto** [comment]
Hey @Fedjmike, we've made some changes to this middleware recently (#407) to validate these options and make sure they are always positive integers. The original idea was similar, but we've decided to prevent zero in the end.

The problem with this approach is that if either `delay` or `max_delay` is zero, that `min` call will always return zero, then we will never have a different value for `sleep`. This means we won't be applying any backoff at all, which kind of defeats the purpose of this middleware.

Setting `delay` to `1` however would have a virtually identical effect of an immediate retry followed by retries with exponentially increasing delays. Which is usually what we mean when we think of setting it to 0.

**Comment by Fedjmike** [comment]
@britto Our use of the middleware is to retry after having resolved some state which caused the initial error. For this purpose we don't want any backoff at all.

If both `delay` and `max_delay` were explicitly set to 0, that would be a clear intention to retry with no delay. How about that?

**Comment by britto** [comment]
Good point. Not sure how the library authors feel about this, but maybe a middle ground solution would be providing multiple middlewares for different retry strategies, or multiple built-in strategies which could be injected to the Retry middleware configuration. That way the code of each strategy would stay focused on a single concern, with clear and documented intentions/behaviors, and also avoiding complex configuration and extra logic at runtime.

**Comment by teamon** [comment]
@britto I think that would be a good approach to separate different retry strategies (immediate, constant, exponential, etc).

I'd be more than happy to accept such contribution.

**Comment by teamon** [comment]
Setting `delay: 0` will cause the delay to always be 0.
