### ISSUE TITLE
Extract Tesla.Multipart to own library?

### ISSUE THREAD

**Issue by hubertlepicki** [teamon/tesla#437]
This is mostly question to maintainers of this library (@teamon and maybe others?), and a matter not strictly related to Tesla but more to other HTTP client libraries in general.

In short: other HTTP clients often don't have support for creation and encoding of Multipart HTTP requests. While we could add a support to creation of Multipart request bodies to other libraries, maybe better option would be to re-use Tesla's implementation and extract it to it's own micro-library instead and rely on that.

As far as I understand, now you can create Multipart body requests using HTTPoison (which delegates this task to hackney), but other clients such as [Finch](https://github.com/keathley/finch) or [Mojito](https://github.com/appcues/mojito) do not support creation of such bodies. And you did great job in Tesla to create generic, streaming Multipart body encoder already.

I have been using [Tesla.Multipart](https://github.com/teamon/tesla/blob/master/lib/tesla/multipart.ex) file in conjunction with Finch already, it works great. But it requires me to have both dependency on Tesla and Finch, and I don't use other functionality of Tesla.

Since the module is pretty much stand-alone, I think the task wouldn't be terribly hard to extract it to own library (and I can assist).

@teamon what do you think?

**Comment by teamon** [comment]
I'm not a big fan of microlibraries. Having a single package for all the adapters and middleware was one of the main goals of tesla to prevent 10-20+ packages and dependency hell. 

Elixir ecosystem provides an excellent support for optional dependencies which tesla relies on heavily, having only one required dependency - mime - which you most probably already have in your app anyway. I do not think depending on tesla package even if you only use `Tesla.Middleware` is a problem.
