### ISSUE TITLE
Make Tesla.Middleware.BaseUrl.apply_base/2 public

### ISSUE THREAD

**Issue by halostatue** [teamon/tesla#443]
I’m implementing an SFMC client using Tesla, and the “Enhanced” packages return two different base URLs for a client on authentication. If you know the client instance ID, you can construct these (`https://#{id}.rest.marketingcloudapis.com/` and `https://#{id}.soap.marketingcloudapis.com/`).

I’m implementing a middleware for SFMC that can both request an authentication token (if the current one has expired or does not exist) but also select and apply the appropriate base URL from the returned authentication response

At the moment, I’m going to be copying / pasting the `BaseUrl` implementation of `apply_base` and `join`, but it would be ideal if I could simply call `Tesla.Middleware.BaseUrl.apply_base/2`.

**Comment by teamon** [comment]
There is no need for that, you can call middleware from within other middleware

```elixir
defmodule SFMC do
  def call(env, next, _opts) do
    url = if smith, do: "aaa", else: "bbb"
    Tesla.Middleware.BaseUrl.call(env, next, url)
  end
end
```

**Comment by halostatue** [comment]
Only if I’m handing off to `BaseUrl`. I have several other steps to do with this as well.

**Comment by halostatue** [comment]
This works. I would suggest that this is worth documenting somewhere.
