### ISSUE TITLE
Feature Request: `Tesla.put_private/3`, `Tesla.get_private/3`

### ISSUE THREAD

**Issue by halostatue** [teamon/tesla#445]
Related to #443 and #444, I could chain some of the functionality I would use for the SFMC client / middleware that I’m building if there were an “approved” way of passing data from middleware to middleware. If this were able to happen, then I might be able to do something like this:

```elixir
middleware = [
  {SFMCAuthMiddleware, provider: SFMCTokenProvider, credentials: %{…}},
  {Tesla.Middleware.BaseUrl, &Tesla.get_private(&1, :sfmc_rest_url)},
]
```

This would be analogous to `Conn.put_private/3` and `Conn.get_private/3`.

**Comment by teamon** [comment]
See https://github.com/teamon/tesla/issues/443#issuecomment-770019359

**Comment by halostatue** [comment]
These appear to not be necessary as it appears that `Tesla.put_opt` can be used similarly for this.
