### ISSUE TITLE
Proxy for Gun HTTP client

### ISSUE THREAD

**Issue by rustra** [teamon/tesla#451]
Hi there,

i'm trying to use proxy with Gun HTTP client and it does not work for me for both public SOCKS5 proxy and local tor service:
```elixir
gun_client = Tesla.client([], Tesla.Adapter.Gun)
Tesla.get(gun_client, "https://api.ipify.org", opts: [adapter: [timeout: 50_000, proxy: {'72.206.181.103', 4145}]])
```

The result I have is `{:error, :timeout`. Am I doing something wrong? Could you please help me with that?

Thanks in advance

**Comment by alex-strizhakov** [comment]
hey!

A proxy can be used only for the gun `master` branch. From [gun docs](https://hexdocs.pm/tesla/Tesla.Adapter.Gun.html)
> :proxy - Proxy for requests. Socks proxy are supported only for gun master branch. Examples: {'localhost', 1234}, {{127, 0, 0, 1}, 1234}, {:socks5, 'localhost', 1234}

And seems that your configuration is not correct. Should work in this way, if you are using gun from `master` branch:

```elixir
adapter: [timeout: 50_000, proxy: {:socks5, {72, 206, 181, 103}, 4145}]
```

**Comment by rustra** [comment]
Hi @alex-strizhakov,

Thanks for your reply! Indeed it's necessary to use the master branch for Gun otherwise the result would be clear: `{:error, "socks protocol is not supported"}`.
I've tried different possible formats for configuring proxy (`{:socks5, {127, 0, 0, 1}, 9150}`, `{:socks5, 'localhost', 9150}` for local Tor service). All the times I had `{:error, :timeout}` while I could use Tor as proxy via Socks5 in a browser.

Could be great if someone could reproduce it. I use Tesla 1.4.0, Gun from master, Elixir 1.10.1, Erlang/OTP 22, on Ubuntu 18 x86_64.

**Comment by teamon** [comment]
Closing this one as not actionable on tesla side - please open an issue in gun repo if this is still a problem.
