### ISSUE TITLE
SSE Client support

### ISSUE THREAD

**Issue by sleipnir** [teamon/tesla#453]
First of all, I would like to praise this excellent http library.

I need to implement an http SSE Server-Sent-Events client and I would like to know if this is possible with this library. If so, is there an example available? If not, could you tell me any alternative to develop an SSE client in Elixir? I know that there are some options for server side implementation, but I couldn't find any example of an SSE client.
Thanks.

**Comment by teamon** [comment]
The best way would be to implement [response streaming](https://github.com/teamon/tesla/issues/271) and a SSE middleware that could parse the stream into proper data structures (one per event)

**Comment by sleipnir** [comment]
Cool. Thanks, I'll take a look at the response streaming

**Comment by teamon** [comment]
I'll close this issue for now, lets continue in #271
