### ISSUE TITLE
Adding information to request/response

### ISSUE THREAD

**Issue by JPYamamoto** [teamon/tesla#458]
How can I put additional information in a `Tesla.Env` that is not necessarily part of the request/response?

For example, I would like to add a timestamp when the response was received. I can use a Middleware to modify the response, but I don't think the parameter fits in any of the existing [fields](https://hexdocs.pm/tesla/Tesla.Env.html#module-fields) of the struct.

Maybe the example is not the best, because there's the telemetry middleware, but I think it communicates the idea.

Would you consider adding a field such as `env.extra`? I could help with a Pull Request if you think that's a good idea.

**Comment by teamon** [comment]
You can use `env.opts` - see how [`Tesla.Middleware.KeepRequest`](https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/keep_request.ex#L30) does it.
