### ISSUE TITLE
Add c:Tesla.Middleware.init/1

### ISSUE THREAD

**Issue by garthk** [teamon/tesla#459]
Further to #129, I might be able to shave a few hundred microseconds off each outbound request in the OpenTelemetry integration if I could do some work just once. Usual pattern, pre-processing the `opts` subsequently handed to `c:call/3`?

**Comment by teamon** [comment]
The problem with `init/1` is that Tesla is fully stateless. It does not start any processes on its own and is not part of supervision tree. You can [create the client dynamically from scratch](https://github.com/teamon/tesla#runtime-middleware). 

Having said that, I'm open for any suggestions here. Also if you post your code maybe we can figure out what's slowing it down. (In my personal experience Tesla code execution is negligible compared to network requests, but YMMV)
