### ISSUE TITLE
Same POST works in HTTPoison, but not in Tesla

### ISSUE THREAD

**Issue by bsollish** [teamon/tesla#464]
This works fine:
{:ok, response} = HTTPoison.post(@url, "show catalogs", [{"X-Presto-User", "test-user"}])

But with this, I get 400 bad request:
{:ok, response} = Tesla.post(@url, "show catalogs", headers: [{"X-Presto-User", "test-user"}])

I don't understand how they are different (or what I have to add/change to get the Tesla version to work)

Thanks

**Comment by teamon** [comment]
Hi,

It's hard to tell without any more details.

Please note that by default tesla uses Erlang's built-in `httpc` adapter and HTTPoison uses `hackney` under the hood. 
I'd recommend plugging in `Tesla.Middleware.Logger` with debug enabled and inspect the request/response details.

**Comment by programisti** [comment]
I fixed this by adding this line to config, it changes default adapter from  `httpc` to `hackney` like HTTPoison does
```elixir
config :tesla, :adapter, Tesla.Adapter.Hackney
```
