### ISSUE TITLE
JSON middleware does not (seem to?) handle `Transfer-Encoding: chunked` correctly.

### ISSUE THREAD

**Issue by queer** [teamon/tesla#466]
I'm using Tesla to write a Docker client. The [route for pulling/creating an image](https://docs.docker.com/engine/api/v1.41/#operation/ImageCreate) returns chunked JSON and the Tesla JSON middleware doesn't handle it correctly. 

**Expected result:**

Tesla handles the chunked JSON properly and returns it as a list.

<details>
<summary>curl example</summary>
<pre><code>
▶  curl -v -XPOST --unix-socket "/var/run/docker.sock" "http:/docker/images/create?fromImage=nginxdemos%2Fhello:latest"
*   Trying /var/run/docker.sock:0...
* Connected to docker (/run/docker.sock) port 80 (#0)
> POST /images/create?fromImage=nginxdemos%2Fhello:latest HTTP/1.1
> Host: docker
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.41
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/20.10.6 (linux)
< Date: Sun, 23 May 2021 05:19:00 GMT
< Transfer-Encoding: chunked
< 
{"status":"Pulling from nginxdemos/hello","id":"latest"}
{"status":"Pulling fs layer","progressDetail":{},"id":"550fe1bea624"}
{"status":"Pulling fs layer","progressDetail":{},"id":"d421ba34525b"}
{"status":"Pulling fs layer","progressDetail":{},"id":"fdcbcb327323"}
{"status":"Pulling fs layer","progressDetail":{},"id":"bfbcec2fc4d5"}
{"status":"Pulling fs layer","progressDetail":{},"id":"0497d4d5654f"}
{"status":"Pulling fs layer","progressDetail":{},"id":"f9518aaa159c"}
{"status":"Pulling fs layer","progressDetail":{},"id":"a70e975849d8"}
{"status":"Waiting","progressDetail":{},"id":"0497d4d5654f"}
{"status":"Waiting","progressDetail":{},"id":"f9518aaa159c"}
{"status":"Waiting","progressDetail":{},"id":"bfbcec2fc4d5"}
{"status":"Downloading","progressDetail":{"current":19730,"total":1970140},"progress":"[\u003e                                                  ]  19.73kB/1.97MB","id":"550fe1bea624"}
{"status":"Downloading","progressDetail":{"current":494,"total":494},"progress":"[==================================================\u003e]     494B/494B","id":"fdcbcb327323"}
{"status":"Download complete","progressDetail":{},"id":"fdcbcb327323"}
{"status":"Downloading","progressDetail":{"current":52428,"total":5174358},"progress":"[\u003e                                                  ]  52.43kB/5.174MB","id":"d421ba34525b"}
{"status":"Verifying Checksum","progressDetail":{},"id":"550fe1bea624"}
{"status":"Download complete","progressDetail":{},"id":"550fe1bea624"}
{"status":"Extracting","progressDetail":{"current":32768,"total":1970140},"progress":"[\u003e                                                  ]  32.77kB/1.97MB","id":"550fe1bea624"}
{"status":"Verifying Checksum","progressDetail":{},"id":"d421ba34525b"}
{"status":"Download complete","progressDetail":{},"id":"d421ba34525b"}
{"status":"Downloading","progressDetail":{"current":609,"total":626},"progress":"[================================================\u003e  ]     609B/626B","id":"bfbcec2fc4d5"}
{"status":"Downloading","progressDetail":{"current":626,"total":626},"progress":"[==================================================\u003e]     626B/626B","id":"bfbcec2fc4d5"}
{"status":"Verifying Checksum","progressDetail":{},"id":"bfbcec2fc4d5"}
{"status":"Download complete","progressDetail":{},"id":"bfbcec2fc4d5"}
{"status":"Extracting","progressDetail":{"current":1933312,"total":1970140},"progress":"[=================================================\u003e ]  1.933MB/1.97MB","id":"550fe1bea624"}
{"status":"Extracting","progressDetail":{"current":1970140,"total":1970140},"progress":"[==================================================\u003e]   1.97MB/1.97MB","id":"550fe1bea624"}
{"status":"Pull complete","progressDetail":{},"id":"550fe1bea624"}
{"status":"Downloading","progressDetail":{"current":182,"total":182},"progress":"[==================================================\u003e]     182B/182B","id":"0497d4d5654f"}
{"status":"Download complete","progressDetail":{},"id":"0497d4d5654f"}
{"status":"Extracting","progressDetail":{"current":65536,"total":5174358},"progress":"[\u003e                                                  ]  65.54kB/5.174MB","id":"d421ba34525b"}
{"status":"Downloading","progressDetail":{"current":357,"total":357},"progress":"[==================================================\u003e]     357B/357B","id":"f9518aaa159c"}
{"status":"Verifying Checksum","progressDetail":{},"id":"f9518aaa159c"}
{"status":"Download complete","progressDetail":{},"id":"f9518aaa159c"}
{"status":"Downloading","progressDetail":{"current":608,"total":4958},"progress":"[======\u003e                                            ]     608B/4.958kB","id":"a70e975849d8"}
{"status":"Downloading","progressDetail":{"current":4958,"total":4958},"progress":"[==================================================\u003e]  4.958kB/4.958kB","id":"a70e975849d8"}
{"status":"Download complete","progressDetail":{},"id":"a70e975849d8"}
{"status":"Extracting","progressDetail":{"current":2621440,"total":5174358},"progress":"[=========================\u003e                         ]  2.621MB/5.174MB","id":"d421ba34525b"}
{"status":"Extracting","progressDetail":{"current":4587520,"total":5174358},"progress":"[============================================\u003e      ]  4.588MB/5.174MB","id":"d421ba34525b"}
{"status":"Extracting","progressDetail":{"current":5174358,"total":5174358},"progress":"[==================================================\u003e]  5.174MB/5.174MB","id":"d421ba34525b"}
{"status":"Extracting","progressDetail":{"current":5174358,"total":5174358},"progress":"[==================================================\u003e]  5.174MB/5.174MB","id":"d421ba34525b"}
{"status":"Pull complete","progressDetail":{},"id":"d421ba34525b"}
{"status":"Extracting","progressDetail":{"current":494,"total":494},"progress":"[==================================================\u003e]     494B/494B","id":"fdcbcb327323"}
{"status":"Extracting","progressDetail":{"current":494,"total":494},"progress":"[==================================================\u003e]     494B/494B","id":"fdcbcb327323"}
{"status":"Pull complete","progressDetail":{},"id":"fdcbcb327323"}
{"status":"Extracting","progressDetail":{"current":626,"total":626},"progress":"[==================================================\u003e]     626B/626B","id":"bfbcec2fc4d5"}
{"status":"Extracting","progressDetail":{"current":626,"total":626},"progress":"[==================================================\u003e]     626B/626B","id":"bfbcec2fc4d5"}
{"status":"Pull complete","progressDetail":{},"id":"bfbcec2fc4d5"}
{"status":"Extracting","progressDetail":{"current":182,"total":182},"progress":"[==================================================\u003e]     182B/182B","id":"0497d4d5654f"}
{"status":"Extracting","progressDetail":{"current":182,"total":182},"progress":"[==================================================\u003e]     182B/182B","id":"0497d4d5654f"}
{"status":"Pull complete","progressDetail":{},"id":"0497d4d5654f"}
{"status":"Extracting","progressDetail":{"current":357,"total":357},"progress":"[==================================================\u003e]     357B/357B","id":"f9518aaa159c"}
{"status":"Extracting","progressDetail":{"current":357,"total":357},"progress":"[==================================================\u003e]     357B/357B","id":"f9518aaa159c"}
{"status":"Pull complete","progressDetail":{},"id":"f9518aaa159c"}
{"status":"Extracting","progressDetail":{"current":4958,"total":4958},"progress":"[==================================================\u003e]  4.958kB/4.958kB","id":"a70e975849d8"}
{"status":"Extracting","progressDetail":{"current":4958,"total":4958},"progress":"[==================================================\u003e]  4.958kB/4.958kB","id":"a70e975849d8"}
{"status":"Pull complete","progressDetail":{},"id":"a70e975849d8"}
{"status":"Digest: sha256:f5a0b2a5fe9af497c4a7c186ef6412bb91ff19d39d6ac24a4997eaed2b0bb334"}
{"status":"Status: Downloaded newer image for nginxdemos/hello:latest"}
* Connection #0 to host docker left intact
</code></pre>
</details>

**Actual result:**

It doesn't work, and an exception is raised:

<details>
<summary>JSON decoding exception</summary>
<pre><code>
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {Tesla.Middleware.JSON, :decode, %Jason.DecodeError{data: "{\"status\":\"Pulling from nginxdemos/hello\",\"id\":\"0.1\"}\r\n{\"status\":\"Pulling fs layer\",\"progressDetail\":{},\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Pulling fs layer\",\"progressDetail\":{},\"id\":\"d421ba34525b\"}\r\n{\"status\":\"Pulling fs layer\",\"progressDetail\":{},\"id\":\"fdcbcb327323\"}\r\n{\"status\":\"Pulling fs layer\",\"progressDetail\":{},\"id\":\"bfbcec2fc4d5\"}\r\n{\"status\":\"Pulling fs layer\",\"progressDetail\":{},\"id\":\"8a1d79bc0870\"}\r\n{\"status\":\"Pulling fs layer\",\"progressDetail\":{},\"id\":\"dbf5f5063dea\"}\r\n{\"status\":\"Pulling fs layer\",\"progressDetail\":{},\"id\":\"68a1d10cc39e\"}\r\n{\"status\":\"Waiting\",\"progressDetail\":{},\"id\":\"dbf5f5063dea\"}\r\n{\"status\":\"Waiting\",\"progressDetail\":{},\"id\":\"bfbcec2fc4d5\"}\r\n{\"status\":\"Waiting\",\"progressDetail\":{},\"id\":\"8a1d79bc0870\"}\r\n{\"status\":\"Waiting\",\"progressDetail\":{},\"id\":\"68a1d10cc39e\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":494,\"total\":494},\"progress\":\"[==================================================\\u003e]     494B/494B\",\"id\":\"fdcbcb327323\"}\r\n{\"status\":\"Verifying Checksum\",\"progressDetail\":{},\"id\":\"fdcbcb327323\"}\r\n{\"status\":\"Download complete\",\"progressDetail\":{},\"id\":\"fdcbcb327323\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":52428,\"total\":5174358},\"progress\":\"[\\u003e                                                  ]  52.43kB/5.174MB\",\"id\":\"d421ba34525b\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":19730,\"total\":1970140},\"progress\":\"[\\u003e                                                  ]  19.73kB/1.97MB\",\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":4675980,\"total\":5174358},\"progress\":\"[=============================================\\u003e     ]  4.676MB/5.174MB\",\"id\":\"d421ba34525b\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":1186189,\"total\":1970140},\"progress\":\"[==============================\\u003e                    ]  1.186MB/1.97MB\",\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":1970140,\"total\":1970140},\"progress\":\"[==================================================\\u003e]   1.97MB/1.97MB\",\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Verifying Checksum\",\"progressDetail\":{},\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Download complete\",\"progressDetail\":{},\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Extracting\",\"progressDetail\":{\"current\":32768,\"total\":1970140},\"progress\":\"[\\u003e                                                  ]  32.77kB/1.97MB\",\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":5174358,\"total\":5174358},\"progress\":\"[==================================================\\u003e]  5.174MB/5.174MB\",\"id\":\"d421ba34525b\"}\r\n{\"status\":\"Download complete\",\"progressDetail\":{},\"id\":\"d421ba34525b\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":609,\"total\":626},\"progress\":\"[================================================\\u003e  ]     609B/626B\",\"id\":\"bfbcec2fc4d5\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":626,\"total\":626},\"progress\":\"[==================================================\\u003e]     626B/626B\",\"id\":\"bfbcec2fc4d5\"}\r\n{\"status\":\"Verifying Checksum\",\"progressDetail\":{},\"id\":\"bfbcec2fc4d5\"}\r\n{\"status\":\"Download complete\",\"progressDetail\":{},\"id\":\"bfbcec2fc4d5\"}\r\n{\"status\":\"Extracting\",\"progressDetail\":{\"current\":1867776,\"total\":1970140},\"progress\":\"[===============================================\\u003e   ]  1.868MB/1.97MB\",\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Extracting\",\"progressDetail\":{\"current\":1970140,\"total\":1970140},\"progress\":\"[==================================================\\u003e]   1.97MB/1.97MB\",\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Pull complete\",\"progressDetail\":{},\"id\":\"550fe1bea624\"}\r\n{\"status\":\"Downloading\",\"progressDetail\":{\"current\":180,\"total\":180},\"progress\":\"[==================================================\\u003e]     180B/180B\",\"id\":\"8a1d79bc0870\"}\r\n{\"status\":\"Verifying Checksum\",\"progressDetail\":{},\"id\":\"8a1d79bc0870\"}\r\n{\"status\":\"Download complete\",\"progressDetail\":{},\"id\":\"8a1d79bc0870\"}\r\n{\"status\":\"Extracting\",\"progressDetail\":{\"current\":65536,\"total\":5174358},\"progress\":\"[\\u003e                                                  ]  65.54kB/5.174MB\",\"id\":\"d421ba34525b\"}\r\n{\"stat" <> ..., position: 55, token: nil}}}
</code></pre>
</details>

**Other:**

Since I'm already using the HTTPoison adapter, I'm using async requests to work around it. It would be nice to be able to do it all in Tesla though.

**Comment by chulkilee** [comment]
I believe the tesla json middleware expects a single json document in the whole response - but the Docker API returns a series of json documents separated by a new line.

If you need to handle each chunk in real time - I'm not sure Tesla supports it.

If you want to parse the doc - you may write own middleware to handle this. This is not a json format :)

**Comment by programisti** [comment]
I fixed this by adding this line to config
```elixir
config :tesla, :adapter, Tesla.Adapter.Hackney
```

**Comment by queer** [comment]
> If you need to handle each chunk in real time - I'm not sure Tesla supports it.

Right, this is mainly what I was wondering about. It'd be nice if Tesla supported it, but ofc it's not required since I can work around it with HTTPoison directly. Feel free to close if this sort of feature is not in-scope for Tesla \^\^

**Comment by chulkilee** [comment]
BTW what is the content-type of the response? It should not be json since it's json stream not json. See https://en.wikipedia.org/wiki/JSON_streaming for several formats for json streaming.

Writing new middleware is easy, so I'd stick with Tesla if you need to use HTTPoison only for this.

Check out https://github.com/teamon/tesla/blob/v1.4.1/lib/tesla/middleware/json.ex#L101 where it parse the whole body as json

```elixir
decode_body(env.body, opts)
```

So.. for example, you can just split the body with new line, and parse like this

```elixir
env.body |> String.split("\n") |> Enum.map(&decode_body(&1, opts))
```

**Comment by queer** [comment]
> BTW what is the content-type of the response? It should not be json since it's json stream not json. 

It is, in fact, `application/json` :D I imagine Docker expects clients to notice the `Transfer-Encoding` header and handle it appropriately.

**Comment by chulkilee** [comment]
Oh, I missed that part. Thanks for the curl example!

I don't think that is the correct expectation since transfer-encoding is a way to encode a payload, not a way to encode a sets of payloads in one request. Seems like Docker has to do this for old clients (https://github.com/moby/moby/pull/8482) :(

**Comment by queer** [comment]
oof, that's incredibly unfortunate and explains the behaviour ):
