### ISSUE TITLE
Middleware for Phoenix.Ecto.SQL.Sandbox

### ISSUE THREAD

**Issue by maltoe** [teamon/tesla#468]
Hello Tesla team,

thanks for making this great library!

We're using Tesla to run integrated tests against our API endpoints. To make these `async: true`, we're using `Phoenix.Ecto.SQL.Sandbox` to share the sandbox transaction with the endpoint (request) process. This tiny middleware helps us doing this:

```elixir
defmodule OurMagicMiddleware do
  @behaviour Tesla.Middleware
  if Application.compile_env!(:my_app, :sql_sandbox) do
    @impl Tesla.Middleware
    def call(env, next, _opts) do
      user_agent = Tesla.get_header(env, "user-agent")

      encoded_metadata =
        MyApp.Repo
        |> Phoenix.Ecto.SQL.Sandbox.metadata_for(self())
        |> Phoenix.Ecto.SQL.Sandbox.encode_metadata()
      
      env
      |> Tesla.put_header("user-agent", "#{user_agent} / #{encoded_metadata}")
      |> Tesla.run(next)
    end
  else
    @impl Tesla.Middleware
    def call(env, next, _opts) do
      Tesla.run(env, next)
    end
  end
end
```

Would you be interested to include this as a middleware shipped with Tesla? We would need to make the dependency on `phoenix_ecto` optional, but IMO it's a really useful little thing.

Best,
malte

**Comment by teamon** [comment]
This seems very specific to your application (especially the part about using user agent header).

However, if you provide some description I'd be more than happy to add it to tesla [Cookbook](https://github.com/teamon/tesla/wiki)

**Comment by maltoe** [comment]
Well it's not really specific to our application, but it's the default header [`Phoenix.Ecto.SQL.Sandbox`](https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/sql/sandbox.ex#L172) uses to transmit the encoded metadata.

It seems I can edit pages in the cookbook, and you're probably right that it is the better place for it, so I'll give it a try. Thanks!
