### ISSUE TITLE
OpenTelemetry Middleware Integration

### ISSUE THREAD

**Issue by RyanSiu1995** [teamon/tesla#475]
OpenTelemetry community is getting bigger and bigger.
Like what we have in the telemetry middleware,
we can have a OpenTelemetryMiddleware to support that integration.

**Comment by wingyplus** [comment]
Sound interesting. I heard that opentelemetry has a bridge for telemetry library (https://github.com/opentelemetry-beam/opentelemetry_telemetry). The other library base on that library (such as phoenix integration https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/mix.exs). I think we can start from another repo to see how hard to integrate with. ;)

**Comment by thiamsantos** [comment]
Tesla already has a `telemetry` middleware. I think would be better to just integrate OpenTelemetry with those telemetry events that tesla publishes as @wingyplus mentioned. As it allows tesla to remain unopinionated to what metrics/tracing protocols and services it supports.

**Comment by teamon** [comment]
Correct me if I'm wrong, but after reading [opentelemetry_plug](https://github.com/opentelemetry-beam/opentelemetry_plug/blob/master/lib/opentelemetry_plug.ex) I see that it attaches to Plug's telemetry events. 

The same way there could be `opentelemetry_tesla` that would attach to telemetry events sent from tesla's `Telemetry` middleware. 

So, if anything, there should be a separate `opentelemetry_tesla` project and not another tesla middleware, right? 🤔

**Comment by wingyplus** [comment]
@teamon correct. One thing I'm not sure is about tracing. In the plug example, they inject a context header to the plug (name Propagation). I'm not sure how to implement it with tesla but I guess it can be done by tesla middleware.

**Comment by RyanSiu1995** [comment]
In general, most of the instrumentors are implemented separately.
The instrumentors itself can be implemented in various way. I have implemented the gRPC instrumentor as an interceptor, like middleware here, before.
If we want to keep using the Erlang telemetry as the base telemetry, I can kickoff the opentelemetry_tesla project and implement the basic functionality quickly.

**Comment by indrekj** [comment]
There's https://github.com/ricardoccpaiva/opentelemetry_tesla which now with some setup integrates with opentelemetry and can do context propagation.

**Comment by teamon** [comment]
Closing this one, feel free to open if there is anything missing or actionable.
