### ISSUE TITLE
`no_return` typespec in `Tesla.Mock.mock/1` & `Tesla.Mock.mock_global/1`

### ISSUE THREAD

**Issue by BasileNouvellet** [teamon/tesla#480]
Hey,

Just wondering why [`Tesla.Mock.mock/1`](https://github.com/teamon/tesla/blob/v1.4.2/lib/tesla/mock.ex#L132) & [`Tesla.Mock.mock_global/1`](https://github.com/teamon/tesla/blob/v1.4.2/lib/tesla/mock.ex#L141) return type is `no_return`?

It emits a Dialyzer warning `has no local return` when using those functions in a dedicated function (not if used directly in `setup_all` though):

![image](https://user-images.githubusercontent.com/24209524/125780927-ab53f960-246c-4061-8313-30c754bb2b03.png)

Warnings are:
 `Function mock_http/1 has no local return.ElixirLS Dialyzer`
 `Function mock_http/0 has no local return.ElixirLS Dialyzer`

Also, the underlying functions they call ([`pdict_set/1`](https://github.com/teamon/tesla/blob/v1.4.2/lib/tesla/mock.ex#L216) & [`agent_set/1`](https://github.com/teamon/tesla/blob/v1.4.2/lib/tesla/mock.ex#L219)) do return a value.

**Comment by teamon** [comment]
@BasileNouvellet Could you check with tesla from `tt/noreturn` branch? https://github.com/teamon/tesla/pull/484

**Comment by BasileNouvellet** [comment]
I confirm that this resolves the issue, thanks!
