### ISSUE TITLE
Refresh Token Middleware

### ISSUE THREAD

**Issue by obsidienne** [teamon/tesla#492]
Hi, 

Is it a good practice to use create a middleware to refresh an access_token.
The use case is the Spotify Web Api, where when the access token is expired, we need to send the refresh token in encoded in application/x-www-form-urlencoded to /api/token endpoint ([ref doc](https://developer.spotify.com/documentation/general/guides/authorization-guide/)) ?

Creating this middleware will need to add the refreshed token in the Tesla response.

What do you think ?

**Comment by teamon** [comment]
In general - yes, creating a custom middleware to handle token refresh is the way to go.
At the same time, every API is different, so I don't think we can have any generic refresh token middleware, unless built for some well-defined common specification.
