### ISSUE TITLE
support Phoenix 1.6

### ISSUE THREAD

**Issue by jalberto** [teamon/tesla#494]
in a fresh generated Phoenix 1.6 project:

```
Failed to use "mime" (version 2.0.1) because
  swoosh (version 1.5.1) requires ~> 1.1 or ~> 2.0
  tesla (version 1.4.3) requires ~> 1.0
  mix.lock specifies 2.0.1


Failed to use "telemetry" because
  phoenix (version 1.6.2) requires ~> 0.4 or ~> 1.0
  tesla (versions 1.4.0 to 1.4.2) requires ~> 0.4
  mix.lock specifies 1.0.0
```

**Comment by xinz** [comment]
Hello @jalberto, there should be a new version of hex.pm release to fix this issue, so far you can try to use the master branch of the repo.

**Comment by jalberto** [comment]
Thanks!

**Comment by dsnipe** [comment]
Any news about when it could be released?

**Comment by hez** [comment]
Bump

**Comment by andyduong1920** [comment]
👋

**Comment by dfrt82** [comment]
Running hex 1.0.1 and generating a phoenix 1.6.5 project you can use tesla 1.4.3 by downgrading mime with
`mix deps.update --all`
However, not sure what's the big deal about relasing a 1.4.4 with the change to mix.exs on master so it works with mime 2.x

**Comment by teamon** [comment]
v1.4.4 has been released https://github.com/teamon/tesla/releases/tag/v1.4.4
