### ISSUE TITLE
JSON middleware: consider allowing to pass accepted content-types 

### ISSUE THREAD

**Issue by casio** [teamon/tesla#50]
I'm working on a client talking to the Vimeo API. They are utilising `Content-type` in a rather dynamic way, see https://developer.vimeo.com/api/spec#version

Ie. it might be `application/vnd.vimeo.video+json`, but could also become `application/vnd.vimeo.error+json` when requests are malformed, etc

Currently the Tesla JSON middleware will refuse to parse response bodies as JSON, when content-type isnt `application/json` or `text/javascript`. 

A means to pass the intended types to the middleware plug would be helpful in such a case.

**Comment by teamon** [comment]
Hey @casio, would #52 solve your case? :)

**Comment by casio** [comment]
It absolutely does...cool, thx! : )

**Comment by amatalai** [comment]
btw I think it's worth to publish next version (0.6.0?) to hex.
5 months passed since last publication and we have new features like this

**Comment by teamon** [comment]
I guess you're right, lemme handle that now.
