### ISSUE TITLE
`Code.ensure_loaded?(:ibrowse)` does not work in production

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#6]
When using tesla in other project and running with `MIX_ENV=prod mix run` causes:

```
** (UndefinedFunctionError) undefined function: Tesla.Adapter.Ibrowse.start/0 (module Tesla.Adapter.Ibrowse is not available)
```

The line causing the `Tesla.Adapter.Ibrowse` not being compiled is https://github.com/monterail/tesla/blob/master/lib/tesla/adapter/ibrowse.ex#L1

Quoting http://elixir-lang.org/docs/v1.0/elixir/Code.html#ensure_loaded/1:

> Elixir also contains an ensure_compiled/1 function that is a superset of ensure_loaded/1.

> Since Elixir’s compilation happens in parallel, in some situations you may need to use a module that was not yet compiled, therefore it can’t even be loaded.

Given that, I wonder if we really need this check at all. Compiling `Tesla.Adapter.Ibrowse` will not cause any error even when `ibrowse` is not specified as dependency.

**Comment by scrogson** [comment]
Because `:ibrowse` is an optional dependency, when you depend on `:tesla` you'll need to add `:ibrowse` as well and instead of having the `Ibrose.start/0`, `:ibrowse` should be added to the list of `:applications` in `mix.exs`. I wouldn't call this a bug, probably should just be explained in the README.

**Comment by teamon** [comment]
I did add `:ibrowse` as dependency.

I just figure out that `Ibrowse.start` should not be used - I need to play with this a little bit and see if it works.

**Comment by teamon** [comment]
Not an issues anymoreNot an issues anymore
