### ISSUE TITLE
Update dependency on Hackney

### ISSUE THREAD

**Issue by hauleth** [teamon/tesla#68]
Version `1.7` is now released.

**Comment by teamon** [comment]
I think we can just relax the dependency and use `>= 1.6.0`.

**Comment by blatyo** [comment]
hackney 1.6.6 is retired. Unfortunately, if you update hackney with tesla present, mix tries to use that version, requiring you to pin 1.6.5.

**Comment by teamon** [comment]
Yesterday was mix_docker day, today it's time for tesla - brace yourselves,
the release is coming!

**Comment by teamon** [comment]
Done in 22258eaef8fb2

**Comment by teamon** [comment]
And here it is - https://github.com/teamon/tesla/releases/tag/v0.7.0
