### ISSUE TITLE
Let Plug exclude specific function

### ISSUE THREAD

**Issue by jeroenbourgois** [teamon/tesla#70]
Hi!

I am trying to use Tesla and so far so good, I can authenticate an api (Google DCM). The authentication part works with the FormUrlEncoded plug, but all of the actual API calls are json responses so I would like to use the JSON plug. However if I enable it, the initial auth call (which performs a JWT token request to Google) does not work when the JSON middleware is enabled. Is there something like

```
plug Tesla.Middleware.JSON, only: [:hello]
plug Tesla.Middleware.FormUrlencoded, only: [:auth]
```

That I can use? Sorry, I am really novice in all of this.

**Comment by amatalai** [comment]
Hi @jeroenbourgois
At the moment there's nothing like only option and I think it's unnecessary. If different middlewares are needed for different functions, you probably should split your module.

Example:
```elixir
defmodule Namespace.Authorization do
  use Tesla

  plug Tesla.Middleware.FormUrlencoded

  def auth do
    # ...
  end
end

defmodule Namespace.Api do
  use Tesla

  plug Tesla.Middleware.JSON

  def hello do
    # ...
  end
end
```

**Comment by jeroenbourgois** [comment]
Ok, pitty, but thanks!
