### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by lasseebert** [teamon/tesla#72]
When updating to a new version of Tesla, it would be nice to have a `CHANGELOG.md`.
In my case, I would like to see if anything I use is broken or if there are new features I care about.

What do the maintainers think about having a changelog in the repo?

**Comment by teamon** [comment]
Have you seen the [releases page](https://github.com/teamon/tesla/releases) ? :)

**Comment by lasseebert** [comment]
Oh. Never mind me ;)

Thx.
