### ISSUE TITLE
:ssl_not_started with default (httpc) adaptor

### ISSUE THREAD

**Issue by randycoulman** [teamon/tesla#74]
I just ran into a problem trying to connect to an https server using Tesla's default adapter.

When running my app normally from the command-line, I'd get the response: `** (Tesla.Error) adapter error: :econnrefused`.  If I loaded the application into iex and ran it from there, it worked fine.

After much digging, I found https://github.com/teamon/tesla/blob/master/lib/tesla/adapter/httpc.ex#L57 which is essentially hiding the true cause of the failure.  After temporarily commenting out that line, I got the following error message: `** (Tesla.Error) adapter error: {:failed_connect, [{:to_address, {'www.toggl.com', 443}}, {:inet, [:inet], :ssl_not_started}]}`.

After some Googling, I found that if I added `:ssl` to the `extra_applications` list in my `mix.exs` file, everything worked fine.

Is there a way for the httpc adaptor to take care of this automatically?  Or is a doc PR in order?  I'm happy to take a crack at a PR for this, but I'd need some direction as to how you'd like it solved.

Thanks for a great library!  I'm really liking it so far!

**Comment by teamon** [comment]
httpc is just the default HTTP client shipped with erlang. 
I guess other adapters like hackney or ibrowse already have :ssl in their dependent applications, so I think it would be fine to simply add :ssl to tesla application list which should solve this issue for everyone.

How does that sound?

**Comment by randycoulman** [comment]
That sounds like it would work.  I can work on a PR for this later this week.
