### ISSUE TITLE
Post request error

### ISSUE THREAD

**Issue by devmarco** [teamon/tesla#76]
I am trying to make a post request following the examples, but I am facing this error where I did not find in any place what it is about and how to solve it.

Tesla Code:
The post body is not being passed through the request

```
defmodule MyModule do
  use Tesla, only: ~w(get post)a

  plug Tesla.Middleware.BaseUrl, "localhost:8080"
  plug Tesla.Middleware.JSON

  adapter Tesla.Adapter.Hackney

  def post_request(props) do
    post("/", props)
  end
end
```
```
MyModule.post_request(%{a: 1})
```

**Issue:**
The post body is not being passed through the request

**Comment by teamon** [comment]
@devmarco Please post the error message, I can't say much from what you posted :(

**Comment by teamon** [comment]
(A hint: try to use "http://localhost:8080" instead of just "localhost:8080")

**Comment by teamon** [comment]
I'm closing this for now, please reopen if you have more details.
