### ISSUE TITLE
Tesla.Middleware.Tuples doesn't work with dynamic client...

### ISSUE THREAD

**Issue by ijcd** [teamon/tesla#86]
I believe I have found an issue whereby ```Tesla.Middleware.Tuples``` does not work if a dynamic client is used. Does this possibly have something to do with the need for ```Tuples``` to be the first middleware listed?

In this instance, I had to prepend the dynamic part w/ ```Tuples``` for it to work.

I needed to do this to get it fully working:

```
    plug Tesla.Middleware.Tuples
    plug Tesla.Middleware.Headers, %{"User-Agent" => "MyConn", "Content-Type" => "application/json"}

    def client(base_url) do
      Tesla.build_client [
        {Tesla.Middleware.Tuples, nil},
        {Tesla.Middleware.BaseUrl, base_url}
      ]
    end
```

**Comment by teamon** [comment]
I'm not sure what do you mean. I've checked and everything seems to be fine.

Given such two modules:


```ex
defmodule X do
  use Tesla

  plug Tesla.Middleware.BaseUrl, "http://httpbin.org"

  def new do
    Tesla.build_client [
      {Tesla.Middleware.Tuples, nil}
    ]
  end
end

defmodule Y do
  use Tesla

  plug Tesla.Middleware.Tuples

  def new do
    Tesla.build_client [
      {Tesla.Middleware.BaseUrl, "http://httpbin.org"}
    ]
  end
end
```


```ex
iex(1)> X.get("/ip")
%Tesla.Env{url: "http://httpbin.org/ip", ...}
# only BaseUrl used

iex(2)> X.new() |> X.get("/ip")
{:ok,
 %Tesla.Env{url: "http://httpbin.org/ip"}, ...}
# Both Tuples and BaseUrl used

iex(3)> Y.get("/ip")
{:error, %Tesla.Error{message: "adapter error: :no_scheme", reason: :no_scheme}}
# Only Tuples used, hence error since "/ip" is not a valid URL

iex(4)> Y.new() |> Y.get("/ip")
{:ok,
 %Tesla.Env{url: "http://httpbin.org/ip", ...}}
# Both middlewares used
```

**Comment by ijcd** [comment]
Interesting. I will test again and report back.

--Ian

**Comment by ijcd** [comment]
Ok, I was able to reproduce it, but I'm not convinced it's an error. Let me know what you think. I have something that looks like this:

```
defmodule Z do
  use Tesla

  plug Tesla.Middleware.Tuples
  plug Tesla.Middleware.Headers, %{"User-Agent" => "MyConn", "Content-Type" => "application/json"}

  def client(base_url) do
    Tesla.build_client [
      {Tesla.Middleware.BaseUrl, base_url}
    ]
  end
end

client = Z.client("http://httpbin.org")

client |> Tesla.request(method: :get, url: "/ip")
|> IO.inspect
```

You'll notice that I am calling `Tesla.request` instead of `Z.request`. If I call the latter it works. The former does not.

I wanted a method that would allow me to specify requests as data and pass then very late to the execution method, so I sought out the `request` method (method can be data). I found it in the Tesla module and didn't realize I should use my module to call it.

**Comment by amatalai** [comment]
Yup, it works this way.

I think we could add something like "common mistakes" to readme. It's not first time when someone uses http functions directly from Tesla module 😢

**Comment by ijcd** [comment]
Maybe there's some way they could be hidden or issue a warning of used
directly.

**Comment by amatalai** [comment]
Direct usage serves different purpose than generated module. For example when I want to check output of my own endpoint I run quick `Tesla.get("http:://localhost:4000/api/something")` in iex. We should not threat this as something bad.

I'm still more convinced to readme/docs improvements. I just need more time to think about it.

**Comment by teamon** [comment]
Closing this for now, I'm not sure we can do much about it.
