### ISSUE TITLE
Middleware not being used

### ISSUE THREAD

**Issue by zamith** [teamon/tesla#88]
I'm having this issue where no middleware is ever used. It's probably something I'm doing wrong, but can't figure out why. Here's the module where I'm using `Tesla`:

```elixir
defmodule Trello do
  use Tesla

  plug Tesla.Middleware.BaseUrl, "https://api.trello.com/1"
  plug Tesla.Middleware.Headers, %{"Content-Type" => "application/json"}
  plug Tesla.Middleware.Tuples
  plug Tesla.Middleware.JSON

  adapter Tesla.Adapter.Httpc

  alias Trello.Card

  def create(:card, card = %Card{}) do
    Tesla.post("/lists/#{card.list_id}/cards", Poison.encode!(%{name: card.name}))
    |> IO.inspect
  end
end
```

If I run this, I get `** (Tesla.Error) adapter error: :no_scheme` because the `BaseUrl` middleware is ignored.

In trying to debug I can see that the `plug` macro definition is being called and that the module attribute `@__middleware__` is being populated correctly. However, when fetching the attribute in the `__before_compile__` callback it is empty. I believe it is because the attribute is only populated after the compilation (from what I could understand), but not sure what to do about it.

I'm using elixir version `1.4.2` and erlang/OTP 19.

**Comment by amatalai** [comment]
Hi,
Instead of `Tesla.post` you should use `post` function generated in your module by `use Tesla` macro.
Besides that `Tuples` should be first middleware to work properly.

Try
```elixir
defmodule Trello do
  use Tesla

  plug Tesla.Middleware.Tuples
  plug Tesla.Middleware.BaseUrl, "https://api.trello.com/1"
  plug Tesla.Middleware.Headers, %{"Content-Type" => "application/json"}
  plug Tesla.Middleware.JSON

  adapter Tesla.Adapter.Httpc

  alias Trello.Card

  def create(:card, card = %Card{}) do
    post("/lists/#{card.list_id}/cards", %{name: card.name})
    |> IO.inspect
  end
end
```

**Comment by zamith** [comment]
Awesome! That works. Thanks.
