### ISSUE TITLE
Broken in production

### ISSUE THREAD

**Issue by dbulic** [teamon/tesla#89]
This works great on my local Ubuntu 16.04.2. It crashes on my server 16.04.
Here is what I see if I open remote_console on server.
```
iex(spectral_core@127.0.0.1)5> resp = Tesla.get "https://google.com"
** (UndefinedFunctionError) function :httpc.request/4 is undefined (module :httpc is not available)
            :httpc.request(:get, {'https://google.com', []}, [autoredirect: false], [])
    (tesla) lib/tesla/adapter/httpc.ex:29: Tesla.Adapter.Httpc.request/2
    (tesla) lib/tesla/adapter/httpc.ex:16: Tesla.Adapter.Httpc.call/2
    (tesla) lib/tesla/middleware/core.ex:5: Tesla.Middleware.Normalize.call/3
```

**Comment by amatalai** [comment]
Hi, try adding `:inets` to your application list in mix.exs

```elixir
def application do
   [extra_applications: [:inets]]
 end
```

**Comment by dbulic** [comment]
Nothing changed. I just tried it on my local machine, using console (instead of remote_console on production) and am getting the same error. Can I use say ibrowse instead of httpc as a default for all calls, without making API client? That would probably solve the issue right away.

Here is some more info (versions of Erlang and Elixir):
```
deploy@production:/app/spectral_core/bin$ sudo ./spectral_core remote_console
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(spectral_core@127.0.0.1)1> Tesla.get "https://google.com"
** (UndefinedFunctionError) function :httpc.request/4 is undefined (module :httpc is not available)
            :httpc.request(:get, {'https://google.com', []}, [autoredirect: false], [])
    (tesla) lib/tesla/adapter/httpc.ex:29: Tesla.Adapter.Httpc.request/2
    (tesla) lib/tesla/adapter/httpc.ex:16: Tesla.Adapter.Httpc.call/2
    (tesla) lib/tesla/middleware/core.ex:5: Tesla.Middleware.Normalize.call/3
iex(spectral_core@127.0.0.1)1> 
```

**Comment by amatalai** [comment]
hmm you probably don't have inets installed with your erlang. This should help: `sudo apt-get install erlang-inets`

But if you prefer to change default adapter then it should be possible by config
```elixir
# config/config.exs

config :tesla, :adapter, :ibrowse
```

**Comment by dbulic** [comment]
I didn't have erlang-inets installed, but even after I installed it and added inets to extra_applications list, it didn't help. I used your config change line and ibrowse worked properly right away.

**Comment by amatalai** [comment]
I'm glad it helped :)

Closing issue, feel free to reopen if there'll be any need to fix httpc in your erlang installation
