### ISSUE TITLE
Make HTTP methods private?

### ISSUE THREAD

**Issue by pikeas** [teamon/tesla#91]
`get()` is a public method added by `use Tesla`. What's the best way to prevent users from directly calling `MyApi.get`, and force them to use only the methods I expose, like `MyApi.widgets`?

Example use cases: required API token, rate limiting middleware.

**Comment by amatalai** [comment]
We tried option to make http methods private but it would create a lot of `function ... is unused` compilation warnings https://github.com/teamon/tesla/pull/46

Best you can do right now is `use Tesla, docs: false`. It'll hide http methods from your module docs.

**Comment by teamon** [comment]
I don't see any good solution right now, I think `docs: false` is the best we can do.
@pikeas please feel free to reopen if needed
