### ISSUE TITLE
Make Caching Middlelayer possible

### ISSUE THREAD

**Issue by leifg** [teamon/tesla#94]
I've been playing around with Tesla and I really like it. Great Work!

I am really keen on implementing a caching middleware but I'm kind of lost. By looking at the current code I don't think it's trivial.

The only solution I came up with so far is something like this (very basic).

```
defmodule CachingMiddleware do
  @ttl = 10

  def call(env, next, _options) do
    case Cache.read(env.url) do
      nil -> 
        result = Tesla.run(env, next)
        Cache.write(env.url, result.body, @ttl)
        result
      cached_body ->  %{env | body: cached_body}
    end
  end
end
```

The problem here is that it depending on the cache backend you can't serialize the elixir data structures so you can only take the body, headers and status code.

The following problem is that in the case of a cache hit, the result will be different from the cache miss returns. The only way around this is knowing about the following middlewares (tuples, json, logger) and running them manually when having a cache hit.

I have found no way in the code to set a flag that will essentially avoid calling the adapter.

Any ideas?

**Comment by teamon** [comment]
If you put the cache middleware right before adapter (i.e. last) the other middleware won't matter :)

**Comment by leifg** [comment]
Just tried that and it works! Thank you.

The only thing that slightly bothers me is that all the normalization comes after that.

A great way to fix this is to make it possible to insert the middleware at a specific point, so that the only thing that comes after my caching middleware is the call to the adapter.

**Comment by teamon** [comment]
@leifg please take a look at #104

**Comment by teamon** [comment]
@leifg ping :)

**Comment by leifg** [comment]
Very Nice! That totally helps!

**Comment by teamon** [comment]
You can check wiki for very simple cache example. I started working on proper http cache middleware, but it’s not ready to be shown yet (stay tuned).

**Comment by venkatd** [comment]
Thanks. I got something basic working but I like the approach you have taken. This may be a bit off topic, but would there be a way to persist the raw http response instead of the erlang `:erlang.term_to_binary` format? I am hoping for something more portable and human readable so other systems can take advantage of the same cache.

**Comment by teamon** [comment]
There is a high chance tesla cache will have adapters to adapters but I’m not sure yet. I’d like tesla to deal with http layer and leave storage to something else. Ideas are welcome! (In the separate Cache issue ;) )

**Comment by teamon** [comment]
(This one #189)

**Comment by leifg** [comment]
> @leifg would you mind sharing the code you have for caching? I'm trying to implement this myself :)

I'm afraid the code is in a proprietary project to which I don't have access to anymore.

But I think you found a solution in the meantime. Right?

**Comment by venkatd** [comment]
@leifg I've found a solution and can post if someone is curious. It was a simple matter of returning in `{:ok, %{env | status: 304, body: body}}` for cached responses as was suggested in the wiki.

**Comment by teamon** [comment]
I'd love to get your feedback on #264
