### ISSUE TITLE
Allow to pass additional errors to `Tesla.Middleware.Tuples`

### ISSUE THREAD

**Issue by Zeeker** [teamon/tesla#96]
I'm currently implementing a wrapper for an external API which serves error objects describing any errors that occur on their part. I've written a middleware which checks for this errors and raises a custom error struct containing the error infos from the response.

Since I want to respond with tuples, instead of raising errors I considered using the `Tuples` middleware but it only catches `Tesla.Error`s. It would be great if I could pass my own errors to rescue from to the middlware.

# Example

```elixir
plug Tesla.Middleware.Tuples, rescue_errors: [My.Error]
```

**Comment by amatalai** [comment]
Hi 
If I understand correctly you want to raise errors in one middleware and then rescue them in another. I think it would be much cleaner and efficient without raising errors at all.

In similar cases I do something like this:
```elixir
defmodule Api do
  use Tesla

  plug Tesla.Middleware.Tuples

  def request do
     get("...") |> parse_result()
  end

  defp parse_result({:error, _}),
    do: {:error, %Error{reason: "request failed"}}
  defp parse_result({:ok, %{body: %{failure_reason: fr}}}),
    do: {:error, %Error{reason: fr}}
  defp parse_result({:ok, %{body: %{value: value}}},
    do: {:ok, value}
```

Let me know what do you think about this approach

**Comment by Zeeker** [comment]
The one issue in this case is that the error generating middleware needs to be the first in the stack or all the other middleware need to be able to handle result tuples.

Raising errors allows a better separation between the error generating and error handling while avoiding impact on other middlewares.
