### ISSUE TITLE
adapter not considered when using `build_client`

### ISSUE THREAD

**Issue by leifg** [teamon/tesla#98]
Consider this:

```elixir
defmodule MyClient do
  use Tesla

  adapter Tesla.Adapter.Hackney

  def client(opts) do

    Tesla.build_client([
      {CustomMiddleware, opts}
    ])
  end
end
```

This code will use `:httpc` (default adapter) as the HTTP adapter and will not take the configuration of hackney into consideration.

Either I'm using it wrong or the information is lost somewhere down building the client.

**Comment by amatalai** [comment]
Hi, are you making requests with functions generated in MyClient module (e.g. MyClient.get) or from Tesla module (e.g. Tesla.get)?

**Comment by leifg** [comment]
I was using `Tesla.get`. It works like a charme with `MyClient .get`. Thanks!

**Comment by amatalai** [comment]
I'm glad it helped
